advanced_graph_problems = [
    "127. Word Ladder",
    "133. Clone Graph",
    "207. Course Schedule",
    "210. Course Schedule II",
    "269. Alien Dictionary",
    "310. Minimum Height Trees",
    "332. Reconstruct Itinerary",
    "399. Evaluate Division",
    "444. Sequence Reconstruction",
    "684. Redundant Connection",
    "685. Redundant Connection II",
    "743. Network Delay Time",
    "765. Couples Holding Hands",
    "787. Cheapest Flights Within K Stops",
    "802. Find Eventual Safe States",
    "834. Sum of Distances in Tree",
    "841. Keys and Rooms",
    "847. Shortest Path Visiting All Nodes",
    "854. K-Similar Strings",
    "882. Reachable Nodes In Subdivided Graph",
    "924. Minimize Malware Spread",
    "928. Minimize Malware Spread II",
    "943. Find the Shortest Superstring",
    "959. Regions Cut By Slashes",
    "1059. All Paths from Source Lead to Destination",
    "1135. Connecting Cities With Minimum Cost",
    "1153. String Transforms Into Another String",
    "1168. Optimize Water Distribution in a Village",
    "1192. Critical Connections in a Network",
    "1203. Sort Items by Groups Respecting Dependencies",
    "1245. Tree Diameter",
    "1334. Find the City With the Smallest Number of Neighbors at a Threshold Distance",
    "1368. Minimum Cost to Make at Least One Valid Path in a Grid",
    "1462. Course Schedule IV",
    "1466. Reorder Routes to Make All Paths Lead to the City Zero",
    "1489. Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree",
    "1514. Path with Maximum Probability",
    "1519. Number of Nodes in the Sub-Tree With the Same Label",
    "1548. The Most Similar Path in a Graph",
    "1568. Minimum Number of Days to Disconnect Island",
    "1579. Remove Max Number of Edges to Keep Graph Fully Traversable",
    "1584. Min Cost to Connect All Points",
    "1615. Maximal Network Rank",
    "1627. Graph Connectivity With Threshold",
    "1631. Path With Minimum Effort",
    "1682. Longest Palindromic Subsequence II",
    "1697. Checking Existence of Edge Length Limited Paths",
    "1722. Minimize Hamming Distance After Swap Operations",
    "1724. Checking Existence of Edge Length Limited Paths II",
    "1743. Restore the Array From Adjacent Pairs",
    "1761. Minimum Degree of a Connected Trio in a Graph",
    "1782. Count Pairs Of Nodes",
    "1786. Number of Restricted Paths From First to Last Node",
    "1835. Find XOR Sum of All Pairs Bitwise AND",
    "1851. Minimum Interval to Include Each Query",
    "1857. Largest Color Value in a Directed Graph",
    "1916. Count Ways to Build Rooms in an Ant Colony",
    "1928. Minimum Cost to Reach Destination in Time",
    "1931. Painting a Grid With Three Different Colors",
    "1948. Delete Duplicate Folders in System",
    "1976. Number of Ways to Arrive at Destination",
    "1994. The Number of Good Subsets",
    "2003. Smallest Missing Genetic Value in Each Subtree",
    "2097. Valid Arrangement of Pairs",
    "2115. Find All Possible Recipes from Given Supplies",
    "2127. Maximum Employees to Be Invited to a Meeting",
    "2142. The Number of Passengers in Each Bus I",
    "2204. Distance to a Cycle in Undirected Graph",
    "2246. Longest Path With Different Adjacent Characters",
    "2290. Minimum Obstacle Removal to Reach Corner",
    "2360. Longest Cycle in a Graph",
    "2392. Build a Matrix With Conditions",
    "2421. Number of Good Paths",
    "2440. Create Components With Same Value",
    "2493. Divide Nodes Into the Maximum Number of Groups",
    "2508. Add Edges to Make Degrees of All Nodes Even",
    "2581. Count Number of Possible Root Nodes",
    "2608. Shortest Cycle in a Graph",
    "2642. Design Graph With Shortest Path Calculator",
    "2662. Minimum Cost of a Path With Special Roads"
]
