advanced_graph_problems = [
    (2, "127. Word Ladder", "Medium"),
    (2, "133. Clone Graph", "Medium"),
    (2, "207. Course Schedule", "Medium"),
    (2, "210. Course Schedule II", "Medium"),
    (2, "310. Minimum Height Trees", "Medium"),
    (2, "332. Reconstruct Itinerary", "Medium"),
    (2, "399. Evaluate Division", "Medium"),
    (2, "684. Redundant Connection", "Medium"),
    (2, "743. Network Delay Time", "Medium"),
    (2, "787. Cheapest Flights Within K Stops", "Medium"),
    (2, "802. Find Eventual Safe States", "Medium"),
    (2, "841. Keys and Rooms", "Medium"),
    (2, "959. Regions Cut By Slashes", "Medium"),
    (2, "1059. All Paths from Source Lead to Destination", "Medium"),
    (2, "1135. Connecting Cities With Minimum Cost", "Medium"),
    (2, "1245. Tree Diameter", "Medium"),
    (2, "1334. Find the City With the Smallest Number of Neighbors at a Threshold Distance", "Medium"),
    (2, "1462. Course Schedule IV", "Medium"),
    (2, "1466. Reorder Routes to Make All Paths Lead to the City Zero", "Medium"),
    (2, "1514. Path with Maximum Probability", "Medium"),
    (2, "1519. Number of Nodes in the Sub-Tree With the Same Label", "Medium"),
    (2, "1584. Min Cost to Connect All Points", "Medium"),
    (2, "1615. Maximal Network Rank", "Medium"),
    (2, "1627. Graph Connectivity With Threshold", "Medium"),
    (2, "1631. Path With Minimum Effort", "Medium"),
    (2, "1743. Restore the Array From Adjacent Pairs", "Medium"),
    (2, "1786. Number of Restricted Paths From First to Last Node", "Medium"),
    (2, "1976. Number of Ways to Arrive at Destination", "Medium"),
    (2, "2115. Find All Possible Recipes from Given Supplies", "Medium"),
    (2, "2246. Longest Path With Different Adjacent Characters", "Medium"),
    (2, "2290. Minimum Obstacle Removal to Reach Corner", "Medium"),
    (2, "2360. Longest Cycle in a Graph", "Medium"),
    (2, "2421. Number of Good Paths", "Medium"),
    (2, "2508. Add Edges to Make Degrees of All Nodes Even", "Medium"),
    (2, "2608. Shortest Cycle in a Graph", "Medium"),
    (2, "2642. Design Graph With Shortest Path Calculator", "Medium"),
    (3, "269. Alien Dictionary", "Hard"),
    (3, "444. Sequence Reconstruction", "Hard"),
    (3, "685. Redundant Connection II", "Hard"),
    (3, "765. Couples Holding Hands", "Hard"),
    (3, "834. Sum of Distances in Tree", "Hard"),
    (3, "847. Shortest Path Visiting All Nodes", "Hard"),
    (3, "854. K-Similar Strings", "Hard"),
    (3, "882. Reachable Nodes In Subdivided Graph", "Hard"),
    (3, "924. Minimize Malware Spread", "Hard"),
    (3, "928. Minimize Malware Spread II", "Hard"),
    (3, "943. Find the Shortest Superstring", "Hard"),
    (3, "1153. String Transforms Into Another String", "Hard"),
    (3, "1168. Optimize Water Distribution in a Village", "Hard"),
    (3, "1192. Critical Connections in a Network", "Hard"),
    (3, "1203. Sort Items by Groups Respecting Dependencies", "Hard"),
    (3, "1368. Minimum Cost to Make at Least One Valid Path in a Grid", "Hard"),
    (3, "1489. Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree", "Hard"),
    (3, "1548. The Most Similar Path in a Graph", "Hard"),
    (3, "1568. Minimum Number of Days to Disconnect Island", "Hard"),
    (3, "1579. Remove Max Number of Edges to Keep Graph Fully Traversable", "Hard"),
    (3, "1682. Longest Palindromic Subsequence II", "Hard"),
    (3, "1697. Checking Existence of Edge Length Limited Paths", "Hard"),
    (3, "1722. Minimize Hamming Distance After Swap Operations", "Hard"),
    (3, "1724. Checking Existence of Edge Length Limited Paths II", "Hard"),
    (3, "1761. Minimum Degree of a Connected Trio in a Graph", "Hard"),
    (3, "1782. Count Pairs Of Nodes", "Hard"),
    (3, "1835. Find XOR Sum of All Pairs Bitwise AND", "Hard"),
    (3, "1851. Minimum Interval to Include Each Query", "Hard"),
    (3, "1857. Largest Color Value in a Directed Graph", "Hard"),
    (3, "1916. Count Ways to Build Rooms in an Ant Colony", "Hard"),
    (3, "1928. Minimum Cost to Reach Destination in Time", "Hard"),
    (3, "1931. Painting a Grid With Three Different Colors", "Hard"),
    (3, "1948. Delete Duplicate Folders in System", "Hard"),
    (3, "1994. The Number of Good Subsets", "Hard"),
    (3, "2003. Smallest Missing Genetic Value in Each Subtree", "Hard"),
    (3, "2097. Valid Arrangement of Pairs", "Hard"),
    (3, "2127. Maximum Employees to Be Invited to a Meeting", "Hard"),
    (3, "2142. The Number of Passengers in Each Bus I", "Hard"),
    (3, "2204. Distance to a Cycle in Undirected Graph", "Hard"),
    (3, "2392. Build a Matrix With Conditions", "Hard"),
    (3, "2440. Create Components With Same Value", "Hard"),
    (3, "2493. Divide Nodes Into the Maximum Number of Groups", "Hard"),
    (3, "2581. Count Number of Possible Root Nodes", "Hard"),
    (3, "2662. Minimum Cost of a Path With Special Roads", "Hard")
]
