array_and_hashing_problems = [
    (1, "1. Two Sum", "Easy"),
    (1, "217. Contains Duplicate", "Easy"),
    (1, "242. Valid Anagram", "Easy"),
    (1, "383. Ransom Note", "Easy"),
    (1, "387. First Unique Character in a String", "Easy"),
    (1, "409. Longest Palindrome", "Easy"),
    (1, "448. Find All Numbers Disappeared in an Array", "Easy"),
    (1, "496. Next Greater Element I", "Easy"),
    (1, "575. Distribute Candies", "Easy"),
    (1, "645. Set Mismatch", "Easy"),
    (1, "724. Find Pivot Index", "Easy"),
    (1, "748. Shortest Completing Word", "Easy"),
    (1, "760. Find Anagram Mappings", "Easy"),
    (1, "771. Jewels and Stones", "Easy"),
    (1, "804. Unique Morse Code Words", "Easy"),
    (1, "884. Uncommon Words from Two Sentences", "Easy"),
    (1, "929. Unique Email Addresses", "Easy"),
    (1, "953. Verifying an Alien Dictionary", "Easy"),
    (1, "961. N-Repeated Element in Size 2N Array", "Easy"),
    (1, "1002. Find Common Characters", "Easy"),
    (1, "1189. Maximum Number of Balloons", "Easy"),
    (1, "1207. Unique Number of Occurrences", "Easy"),
    (1, "1365. How Many Numbers Are Smaller Than the Current Number", "Easy"),
    (1, "1436. Destination City", "Easy"),
    (1, "1512. Number of Good Pairs", "Easy"),
    (1, "1832. Check if the Sentence Is Pangram", "Easy"),
    (1, "2351. First Letter to Appear Twice", "Easy"),
    (2, "36. Valid Sudoku", "Medium"),
    (2, "49. Group Anagrams", "Medium"),
    (2, "238. Product of Array Except Self", "Medium"),
    (2, "271. Encode and Decode Strings", "Medium"),
    (2, "347. Top K Frequent Elements", "Medium"),
    (2, "525. Contiguous Array", "Medium"),
    (2, "535. Encode and Decode TinyURL", "Medium"),
    (2, "560. Subarray Sum Equals K", "Medium"),
    (2, "706. Design HashMap", "Medium"),
    (2, "811. Subdomain Visit Count", "Medium"),
    (2, "846. Hand of Straights", "Medium"),
    (2, "1048. Longest String Chain", "Medium"),
    (2, "1657. Determine if Two Strings Are Close", "Medium"),
    (2, "1679. Max Number of K-Sum Pairs", "Medium"),
    (2, "2215. Find the Difference of Two Arrays", "Medium"),
    (3, "128. Longest Consecutive Sequence", "Hard"),
    (3, "1074. Number of Submatrices That Sum to Target", "Hard")
]
