array_and_hashing_problems = [
    "1. Two Sum",
    "36. Valid Sudoku",
    "49. Group Anagrams",
    "128. Longest Consecutive Sequence",
    "217. Contains Duplicate",
    "238. Product of Array Except Self",
    "242. Valid Anagram",
    "271. Encode and Decode Strings",
    "347. Top K Frequent Elements",
    "383. Ransom Note",
    "387. First Unique Character in a String",
    "409. Longest Palindrome",
    "448. Find All Numbers Disappeared in an Array",
    "496. Next Greater Element I",
    "525. Contiguous Array",
    "535. Encode and Decode TinyURL",
    "560. Subarray Sum Equals K",
    "575. Distribute Candies",
    "645. Set Mismatch",
    "706. Design HashMap",
    "724. Find Pivot Index",
    "748. Shortest Completing Word",
    "760. Find Anagram Mappings",
    "771. Jewels and Stones",
    "804. Unique Morse Code Words",
    "811. Subdomain Visit Count",
    "846. Hand of Straights",
    "884. Uncommon Words from Two Sentences",
    "929. Unique Email Addresses",
    "953. Verifying an Alien Dictionary",
    "961. N-Repeated Element in Size 2N Array",
    "1002. Find Common Characters",
    "1048. Longest String Chain",
    "1074. Number of Submatrices That Sum to Target",
    "1189. Maximum Number of Balloons",
    "1207. Unique Number of Occurrences",
    "1365. How Many Numbers Are Smaller Than the Current Number",
    "1436. Destination City",
    "1512. Number of Good Pairs",
    "1657. Determine if Two Strings Are Close",
    "1679. Max Number of K-Sum Pairs",
    "1832. Check if the Sentence Is Pangram",
    "2215. Find the Difference of Two Arrays",
    "2351. First Letter to Appear Twice"
]
