backtracking_problems = [
    "17. Letter Combinations of a Phone Number",
    "22. Generate Parentheses",
    "37. Sudoku Solver",
    "39. Combination Sum",
    "40. Combination Sum II",
    "46. Permutations",
    "47. Permutations II",
    "51. N-Queens",
    "52. N-Queens II",
    "77. Combinations",
    "78. Subsets",
    "79. Word Search",
    "90. Subsets II",
    "93. Restore IP Addresses",
    "95. Unique Binary Search Trees II",
    "113. Path Sum II",
    "126. Word Ladder II",
    "131. Palindrome Partitioning",
    "140. Word Break II",
    "211. Design Add and Search Words Data Structure",
    "212. Word Search II",
    "216. Combination Sum III",
    "254. Factor Combinations",
    "267. Palindrome Permutation II",
    "291. Word Pattern II",
    "301. Remove Invalid Parentheses",
    "306. Additive Number",
    "320. Generalized Abbreviation",
    "351. Android Unlock Patterns",
    "357. Count Numbers with Unique Digits",
    "401. Binary Watch",
    "411. Minimum Unique Word Abbreviation",
    "489. Robot Room Cleaner",
    "491. Increasing Subsequences",
    "526. Beautiful Arrangement",
    "691. Stickers to Spell Word",
    "784. Letter Case Permutation",
    "797. All Paths From Source to Target",
    "842. Split Array into Fibonacci Sequence",
    "980. Unique Paths III",
    "996. Number of Squareful Arrays",
    "1079. Letter Tile Possibilities",
    "1087. Brace Expansion",
    "1219. Path with Maximum Gold",
    "1239. Maximum Length of a Concatenated String with Unique Characters",
    "1240. Tiling a Rectangle with the Fewest Squares",
    "1286. Iterator for Combination",
    "1306. Jump Game III",
    "1415. The k-th Lexicographical String of All Happy Strings of Length n",
    "1457. Pseudo-Palindromic Paths in a Binary Tree",
    "1593. Split a String Into the Max Number of Unique Substrings",
    "1641. Count Sorted Vowel Strings",
    "1655. Distribute Repeating Integers",
    "1681. Minimum Incompatibility",
    "1723. Find Minimum Time to Finish All Jobs",
    "1755. Closest Subsequence Sum",
    "1774. Closest Dessert Cost",
    "1799. Maximize Score After N Operations",
    "1849. Splitting a String Into Descending Consecutive Values",
    "1947. Maximum Compatibility Score Sum",
    "1980. Find Unique Binary String",
    "2002. Maximum Product of the Length of Two Palindromic Subsequences",
    "2044. Count Number of Maximum Bitwise-OR Subsets",
    "2048. Next Greater Numerically Balanced Number",
    "2151. Maximum Good People Based on Statements",
    "2212. Maximum Points in an Archery Competition",
    "2305. Fair Distribution of Cookies",
    "2397. Maximum Rows Covered by Columns",
    "2698. Find the Punishment Number of an Integer"
]
