backtracking_problems = [
    (1, "17. Letter Combinations of a Phone Number", "Easy"),
    (1, "77. Combinations", "Easy"),
    (1, "78. Subsets", "Easy"),
    (1, "401. Binary Watch", "Easy"),
    (1, "784. Letter Case Permutation", "Easy"),
    (1, "1980. Find Unique Binary String", "Easy"),
    (2, "22. Generate Parentheses", "Medium"),
    (2, "39. Combination Sum", "Medium"),
    (2, "40. Combination Sum II", "Medium"),
    (2, "46. Permutations", "Medium"),
    (2, "47. Permutations II", "Medium"),
    (2, "79. Word Search", "Medium"),
    (2, "90. Subsets II", "Medium"),
    (2, "93. Restore IP Addresses", "Medium"),
    (2, "95. Unique Binary Search Trees II", "Medium"),
    (2, "113. Path Sum II", "Medium"),
    (2, "131. Palindrome Partitioning", "Medium"),
    (2, "211. Design Add and Search Words Data Structure", "Medium"),
    (2, "216. Combination Sum III", "Medium"),
    (2, "254. Factor Combinations", "Medium"),
    (2, "306. Additive Number", "Medium"),
    (2, "357. Count Numbers with Unique Digits", "Medium"),
    (2, "491. Increasing Subsequences", "Medium"),
    (2, "526. Beautiful Arrangement", "Medium"),
    (2, "797. All Paths From Source to Target", "Medium"),
    (2, "842. Split Array into Fibonacci Sequence", "Medium"),
    (2, "1079. Letter Tile Possibilities", "Medium"),
    (2, "1087. Brace Expansion", "Medium"),
    (2, "1219. Path with Maximum Gold", "Medium"),
    (2, "1239. Maximum Length of a Concatenated String with Unique Characters", "Medium"),
    (2, "1286. Iterator for Combination", "Medium"),
    (2, "1306. Jump Game III", "Medium"),
    (2, "1415. The k-th Lexicographical String of All Happy Strings of Length n", "Medium"),
    (2, "1457. Pseudo-Palindromic Paths in a Binary Tree", "Medium"),
    (2, "1593. Split a String Into the Max Number of Unique Substrings", "Medium"),
    (2, "1641. Count Sorted Vowel Strings", "Medium"),
    (2, "1774. Closest Dessert Cost", "Medium"),
    (2, "1849. Splitting a String Into Descending Consecutive Values", "Medium"),
    (2, "2002. Maximum Product of the Length of Two Palindromic Subsequences", "Medium"),
    (2, "2044. Count Number of Maximum Bitwise-OR Subsets", "Medium"),
    (2, "2048. Next Greater Numerically Balanced Number", "Medium"),
    (2, "2212. Maximum Points in an Archery Competition", "Medium"),
    (2, "2305. Fair Distribution of Cookies", "Medium"),
    (2, "2397. Maximum Rows Covered by Columns", "Medium"),
    (2, "2698. Find the Punishment Number of an Integer", "Medium"),
    (3, "37. Sudoku Solver", "Hard"),
    (3, "51. N-Queens", "Hard"),
    (3, "52. N-Queens II", "Hard"),
    (3, "126. Word Ladder II", "Hard"),
    (3, "140. Word Break II", "Hard"),
    (3, "212. Word Search II", "Hard"),
    (3, "267. Palindrome Permutation II", "Hard"),
    (3, "291. Word Pattern II", "Hard"),
    (3, "301. Remove Invalid Parentheses", "Hard"),
    (3, "320. Generalized Abbreviation", "Hard"),
    (3, "351. Android Unlock Patterns", "Hard"),
    (3, "411. Minimum Unique Word Abbreviation", "Hard"),
    (3, "489. Robot Room Cleaner", "Hard"),
    (3, "691. Stickers to Spell Word", "Hard"),
    (3, "980. Unique Paths III", "Hard"),
    (3, "996. Number of Squareful Arrays", "Hard"),
    (3, "1240. Tiling a Rectangle with the Fewest Squares", "Hard"),
    (3, "1655. Distribute Repeating Integers", "Hard"),
    (3, "1681. Minimum Incompatibility", "Hard"),
    (3, "1723. Find Minimum Time to Finish All Jobs", "Hard"),
    (3, "1755. Closest Subsequence Sum", "Hard"),
    (3, "1799. Maximize Score After N Operations", "Hard"),
    (3, "1947. Maximum Compatibility Score Sum", "Hard"),
    (3, "2151. Maximum Good People Based on Statements", "Hard")
]
