binary_search_problems = [
    (1, "35. Search Insert Position", "Easy"),
    (1, "69. Sqrt(x)", "Easy"),
    (1, "278. First Bad Version", "Easy"),
    (1, "367. Valid Perfect Square", "Easy"),
    (1, "374. Guess Number Higher or Lower", "Easy"),
    (1, "441. Arranging Coins", "Easy"),
    (1, "704. Binary Search", "Easy"),
    (1, "744. Find Smallest Letter Greater Than Target", "Easy"),
    (1, "852. Peak Index in a Mountain Array", "Easy"),
    (2, "29. Divide Two Integers", "Medium"),
    (2, "33. Search in Rotated Sorted Array", "Medium"),
    (2, "34. Find First and Last Position of Element in Sorted Array", "Medium"),
    (2, "50. Pow(x, n)", "Medium"),
    (2, "74. Search a 2D Matrix", "Medium"),
    (2, "81. Search in Rotated Sorted Array II", "Medium"),
    (2, "153. Find Minimum in Rotated Sorted Array", "Medium"),
    (2, "162. Find Peak Element", "Medium"),
    (2, "222. Count Complete Tree Nodes", "Medium"),
    (2, "240. Search a 2D Matrix II", "Medium"),
    (2, "275. H-Index II", "Medium"),
    (2, "287. Find the Duplicate Number", "Medium"),
    (2, "300. Longest Increasing Subsequence", "Medium"),
    (2, "378. Kth Smallest Element in a Sorted Matrix", "Medium"),
    (2, "436. Find Right Interval", "Medium"),
    (2, "454. 4Sum II", "Medium"),
    (2, "475. Heaters", "Medium"),
    (2, "528. Random Pick with Weight", "Medium"),
    (2, "540. Single Element in a Sorted Array", "Medium"),
    (2, "658. Find K Closest Elements", "Medium"),
    (2, "875. Koko Eating Bananas", "Medium"),
    (2, "981. Time Based Key-Value Store", "Medium"),
    (2, "1011. Capacity To Ship Packages Within D Days", "Medium"),
    (2, "1283. Find the Smallest Divisor Given a Threshold", "Medium"),
    (2, "1300. Sum of Mutated Array Closest to Target", "Medium"),
    (2, "1482. Minimum Number of Days to Make m Bouquets", "Medium"),
    (2, "1552. Magnetic Force Between Two Balls", "Medium"),
    (2, "1760. Minimum Limit of Balls in a Bag", "Medium"),
    (2, "1870. Minimum Speed to Arrive on Time", "Medium"),
    (2, "2187. Minimum Time to Complete Trips", "Medium"),
    (2, "2300. Successful Pairs of Spells and Potions", "Medium"),
    (3, "4. Median of Two Sorted Arrays", "Hard"),
    (3, "154. Find Minimum in Rotated Sorted Array II", "Hard"),
    (3, "174. Dungeon Game", "Hard"),
    (3, "352. Data Stream as Disjoint Intervals", "Hard"),
    (3, "354. Russian Doll Envelopes", "Hard"),
    (3, "363. Max Sum of Rectangle No Larger Than K", "Hard"),
    (3, "410. Split Array Largest Sum", "Hard"),
    (3, "483. Smallest Good Base", "Hard"),
    (3, "497. Random Point in Non-overlapping Rectangles", "Hard"),
    (3, "644. Maximum Average Subarray II", "Hard"),
    (3, "668. Kth Smallest Number in Multiplication Table", "Hard"),
    (3, "719. Find K-th Smallest Pair Distance", "Hard"),
    (3, "774. Minimize Max Distance to Gas Station", "Hard"),
    (3, "778. Swim in Rising Water", "Hard"),
    (3, "786. K-th Smallest Prime Fraction", "Hard"),
    (3, "793. Preimage Size of Factorial Zeroes Function", "Hard"),
    (3, "878. Nth Magical Number", "Hard"),
    (3, "1201. Ugly Number III", "Hard"),
    (3, "1235. Maximum Profit in Job Scheduling", "Hard")
]
