binary_search_problems = [
    "4. Median of Two Sorted Arrays",
    "29. Divide Two Integers",
    "33. Search in Rotated Sorted Array",
    "34. Find First and Last Position of Element in Sorted Array",
    "35. Search Insert Position",
    "50. Pow(x, n)",
    "69. Sqrt(x)",
    "74. Search a 2D Matrix",
    "81. Search in Rotated Sorted Array II",
    "153. Find Minimum in Rotated Sorted Array",
    "154. Find Minimum in Rotated Sorted Array II",
    "162. Find Peak Element",
    "174. Dungeon Game",
    "222. Count Complete Tree Nodes",
    "240. Search a 2D Matrix II",
    "275. H-Index II",
    "278. First Bad Version",
    "287. Find the Duplicate Number",
    "300. Longest Increasing Subsequence",
    "352. Data Stream as Disjoint Intervals",
    "354. Russian Doll Envelopes",
    "363. Max Sum of Rectangle No Larger Than K",
    "367. Valid Perfect Square",
    "374. Guess Number Higher or Lower",
    "378. Kth Smallest Element in a Sorted Matrix",
    "410. Split Array Largest Sum",
    "436. Find Right Interval",
    "441. Arranging Coins",
    "454. 4Sum II",
    "475. Heaters",
    "483. Smallest Good Base",
    "497. Random Point in Non-overlapping Rectangles",
    "528. Random Pick with Weight",
    "540. Single Element in a Sorted Array",
    "644. Maximum Average Subarray II",
    "658. Find K Closest Elements",
    "668. Kth Smallest Number in Multiplication Table",
    "704. Binary Search",
    "719. Find K-th Smallest Pair Distance",
    "744. Find Smallest Letter Greater Than Target",
    "774. Minimize Max Distance to Gas Station",
    "778. Swim in Rising Water",
    "786. K-th Smallest Prime Fraction",
    "793. Preimage Size of Factorial Zeroes Function",
    "852. Peak Index in a Mountain Array",
    "875. Koko Eating Bananas",
    "878. Nth Magical Number",
    "981. Time Based Key-Value Store",
    "1011. Capacity To Ship Packages Within D Days",
    "1201. Ugly Number III",
    "1235. Maximum Profit in Job Scheduling",
    "1283. Find the Smallest Divisor Given a Threshold",
    "1300. Sum of Mutated Array Closest to Target",
    "1482. Minimum Number of Days to Make m Bouquets",
    "1552. Magnetic Force Between Two Balls",
    "1760. Minimum Limit of Balls in a Bag",
    "1870. Minimum Speed to Arrive on Time",
    "2187. Minimum Time to Complete Trips",
    "2300. Successful Pairs of Spells and Potions"
]
