bit_manipulation_problems = [
    "78. Subsets",
    "136. Single Number",
    "137. Single Number II",
    "169. Majority Element",
    "190. Reverse Bits",
    "191. Number of 1 Bits",
    "201. Bitwise AND of Numbers Range",
    "231. Power of Two",
    "260. Single Number III",
    "268. Missing Number",
    "318. Maximum Product of Word Lengths",
    "338. Counting Bits",
    "342. Power of Four",
    "371. Sum of Two Integers",
    "389. Find the Difference",
    "393. UTF-8 Validation",
    "397. Integer Replacement",
    "401. Binary Watch",
    "405. Convert a Number to Hexadecimal",
    "421. Maximum XOR of Two Numbers in an Array",
    "461. Hamming Distance",
    "476. Number Complement",
    "477. Total Hamming Distance",
    "693. Binary Number with Alternating Bits",
    "762. Prime Number of Set Bits in Binary Representation",
    "784. Letter Case Permutation",
    "1009. Complement of Base 10 Integer",
    "1178. Number of Valid Words for Each Puzzle",
    "1238. Circular Permutation in Binary Representation",
    "1290. Convert Binary Number in a Linked List to Integer",
    "1318. Minimum Flips to Make a OR b Equal to c",
    "1342. Number of Steps to Reduce a Number to Zero",
    "1356. Sort Integers by The Number of 1 Bits",
    "1371. Find the Longest Substring Containing Vowels in Even Counts",
    "1380. Lucky Numbers in a Matrix",
    "1442. Count Triplets That Can Form Two Arrays of Equal XOR",
    "1457. Pseudo-Palindromic Paths in a Binary Tree",
    "1461. Check If a String Contains All Binary Codes of Size K",
    "1486. XOR Operation in an Array",
    "1611. Minimum One Bit Operations to Make Integers Zero",
    "1648. Sell Diminishing-Valued Colored Balls",
    "1680. Concatenation of Consecutive Binary Numbers",
    "1684. Count the Number of Consistent Strings",
    "1720. Decode XORed Array",
    "1734. Decode XORed Permutation",
    "1738. Find Kth Largest XOR Coordinate Value",
    "1774. Closest Dessert Cost",
    "1780. Check if Number is a Sum of Powers of Three",
    "1799. Maximize Score After N Operations",
    "1829. Maximum XOR for Each Query",
    "1835. Find XOR Sum of All Pairs Bitwise AND",
    "1863. Sum of All Subset XOR Totals",
    "1884. Egg Drop With 2 Eggs and N Floors",
    "1980. Find Unique Binary String",
    "1986. Minimum Number of Work Sessions to Finish the Tasks",
    "2044. Count Number of Maximum Bitwise-OR Subsets",
    "2135. Count Words Obtained After Adding a Letter",
    "2157. Groups of Strings",
    "2166. Design Bitset",
    "2220. Minimum Bit Flips to Convert Number",
    "2275. Largest Combination With Bitwise AND Greater Than Zero",
    "2317. Maximum XOR After Operations",
    "2401. Longest Nice Subarray",
    "2425. Bitwise XOR of All Pairings",
    "2429. Minimize XOR",
    "2433. Find The Original Array of Prefix Xor",
    "2527. Find Xor-Beauty of Array",
    "2546. Apply Bitwise Operations to Make Strings Equal",
    "2564. Substring XOR Queries",
    "2571. Minimum Operations to Reduce an Integer to 0"
]
