bit_manipulation_problems = [
    (1, "136. Single Number", "Easy"),
    (1, "169. Majority Element", "Easy"),
    (1, "190. Reverse Bits", "Easy"),
    (1, "191. Number of 1 Bits", "Easy"),
    (1, "231. Power of Two", "Easy"),
    (1, "268. Missing Number", "Easy"),
    (1, "342. Power of Four", "Easy"),
    (1, "389. Find the Difference", "Easy"),
    (1, "401. Binary Watch", "Easy"),
    (1, "461. Hamming Distance", "Easy"),
    (1, "476. Number Complement", "Easy"),
    (1, "693. Binary Number with Alternating Bits", "Easy"),
    (1, "762. Prime Number of Set Bits in Binary Representation", "Easy"),
    (1, "1009. Complement of Base 10 Integer", "Easy"),
    (1, "1290. Convert Binary Number in a Linked List to Integer", "Easy"),
    (1, "1342. Number of Steps to Reduce a Number to Zero", "Easy"),
    (1, "1356. Sort Integers by The Number of 1 Bits", "Easy"),
    (1, "1486. XOR Operation in an Array", "Easy"),
    (1, "1684. Count the Number of Consistent Strings", "Easy"),
    (1, "1720. Decode XORed Array", "Easy"),
    (1, "1980. Find Unique Binary String", "Easy"),
    (1, "2220. Minimum Bit Flips to Convert Number", "Easy"),
    (2, "78. Subsets", "Medium"),
    (2, "137. Single Number II", "Medium"),
    (2, "201. Bitwise AND of Numbers Range", "Medium"),
    (2, "260. Single Number III", "Medium"),
    (2, "318. Maximum Product of Word Lengths", "Medium"),
    (2, "338. Counting Bits", "Medium"),
    (2, "371. Sum of Two Integers", "Medium"),
    (2, "393. UTF-8 Validation", "Medium"),
    (2, "397. Integer Replacement", "Medium"),
    (2, "405. Convert a Number to Hexadecimal", "Medium"),
    (2, "421. Maximum XOR of Two Numbers in an Array", "Medium"),
    (2, "477. Total Hamming Distance", "Medium"),
    (2, "784. Letter Case Permutation", "Medium"),
    (2, "1238. Circular Permutation in Binary Representation", "Medium"),
    (2, "1318. Minimum Flips to Make a OR b Equal to c", "Medium"),
    (2, "1371. Find the Longest Substring Containing Vowels in Even Counts", "Medium"),
    (2, "1442. Count Triplets That Can Form Two Arrays of Equal XOR", "Medium"),
    (2, "1457. Pseudo-Palindromic Paths in a Binary Tree", "Medium"),
    (2, "1461. Check If a String Contains All Binary Codes of Size K", "Medium"),
    (2, "1680. Concatenation of Consecutive Binary Numbers", "Medium"),
    (2, "1734. Decode XORed Permutation", "Medium"),
    (2, "1738. Find Kth Largest XOR Coordinate Value", "Medium"),
    (2, "1774. Closest Dessert Cost", "Medium"),
    (2, "1780. Check if Number is a Sum of Powers of Three", "Medium"),
    (2, "1829. Maximum XOR for Each Query", "Medium"),
    (2, "1863. Sum of All Subset XOR Totals", "Medium"),
    (2, "1986. Minimum Number of Work Sessions to Finish the Tasks", "Medium"),
    (2, "2044. Count Number of Maximum Bitwise-OR Subsets", "Medium"),
    (2, "2166. Design Bitset", "Medium"),
    (2, "2275. Largest Combination With Bitwise AND Greater Than Zero", "Medium"),
    (2, "2317. Maximum XOR After Operations", "Medium"),
    (2, "2425. Bitwise XOR of All Pairings", "Medium"),
    (2, "2429. Minimize XOR", "Medium"),
    (2, "2433. Find The Original Array of Prefix Xor", "Medium"),
    (2, "2527. Find Xor-Beauty of Array", "Medium"),
    (2, "2546. Apply Bitwise Operations to Make Strings Equal", "Medium"),
    (2, "2564. Substring XOR Queries", "Medium"),
    (2, "2571. Minimum Operations to Reduce an Integer to 0", "Medium"),
    (3, "1178. Number of Valid Words for Each Puzzle", "Hard"),
    (3, "1611. Minimum One Bit Operations to Make Integers Zero", "Hard"),
    (3, "1648. Sell Diminishing-Valued Colored Balls", "Hard"),
    (3, "1799. Maximize Score After N Operations", "Hard"),
    (3, "1835. Find XOR Sum of All Pairs Bitwise AND", "Hard"),
    (3, "1884. Egg Drop With 2 Eggs and N Floors", "Hard"),
    (3, "2135. Count Words Obtained After Adding a Letter", "Hard"),
    (3, "2157. Groups of Strings", "Hard"),
    (3, "2401. Longest Nice Subarray", "Hard")
]
