graph_problems = [
    (1, "200. Number of Islands", "Easy"),
    (1, "997. Find the Town Judge", "Easy"),
    (1, "1436. Destination City", "Easy"),
    (1, "1791. Find Center of Star Graph", "Easy"),
    (2, "133. Clone Graph", "Medium"),
    (2, "207. Course Schedule", "Medium"),
    (2, "210. Course Schedule II", "Medium"),
    (2, "261. Graph Valid Tree", "Medium"),
    (2, "310. Minimum Height Trees", "Medium"),
    (2, "323. Number of Connected Components in an Undirected Graph", "Medium"),
    (2, "332. Reconstruct Itinerary", "Medium"),
    (2, "399. Evaluate Division", "Medium"),
    (2, "417. Pacific Atlantic Water Flow", "Medium"),
    (2, "433. Minimum Genetic Mutation", "Medium"),
    (2, "547. Number of Provinces", "Medium"),
    (2, "684. Redundant Connection", "Medium"),
    (2, "743. Network Delay Time", "Medium"),
    (2, "785. Is Graph Bipartite?", "Medium"),
    (2, "787. Cheapest Flights Within K Stops", "Medium"),
    (2, "797. All Paths From Source to Target", "Medium"),
    (2, "802. Find Eventual Safe States", "Medium"),
    (2, "841. Keys and Rooms", "Medium"),
    (2, "851. Loud and Rich", "Medium"),
    (2, "886. Possible Bipartition", "Medium"),
    (2, "934. Shortest Bridge", "Medium"),
    (2, "947. Most Stones Removed with Same Row or Column", "Medium"),
    (2, "959. Regions Cut By Slashes", "Medium"),
    (2, "990. Satisfiability of Equality Equations", "Medium"),
    (2, "1020. Number of Enclaves", "Medium"),
    (2, "1042. Flower Planting With No Adjacent", "Medium"),
    (2, "1162. As Far from Land as Possible", "Medium"),
    (2, "1202. Smallest String With Swaps", "Medium"),
    (2, "1254. Number of Closed Islands", "Medium"),
    (2, "1267. Count Servers that Communicate", "Medium"),
    (2, "1319. Number of Operations to Make Network Connected", "Medium"),
    (2, "1334. Find the City With the Smallest Number of Neighbors at a Threshold Distance", "Medium"),
    (2, "1361. Validate Binary Tree Nodes", "Medium"),
    (2, "1391. Check if There is a Valid Path in a Grid", "Medium"),
    (2, "1462. Course Schedule IV", "Medium"),
    (2, "1466. Reorder Routes to Make All Paths Lead to the City Zero", "Medium"),
    (2, "1514. Path with Maximum Probability", "Medium"),
    (2, "1519. Number of Nodes in the Sub-Tree With the Same Label", "Medium"),
    (2, "1557. Minimum Number of Vertices to Reach All Nodes", "Medium"),
    (2, "1584. Min Cost to Connect All Points", "Medium"),
    (2, "1615. Maximal Network Rank", "Medium"),
    (2, "1627. Graph Connectivity With Threshold", "Medium"),
    (2, "1631. Path With Minimum Effort", "Medium"),
    (2, "1926. Nearest Exit from Entrance in Maze", "Medium"),
    (2, "2039. The Time When the Network Becomes Idle", "Medium"),
    (2, "2065. Maximum Path Quality of a Graph", "Medium"),
    (2, "2115. Find All Possible Recipes from Given Supplies", "Medium"),
    (2, "2192. All Ancestors of a Node in a Directed Acyclic Graph", "Medium"),
    (2, "2246. Longest Path With Different Adjacent Characters", "Medium"),
    (2, "2285. Maximum Total Importance of Roads", "Medium"),
    (2, "2316. Count Unreachable Pairs of Nodes in an Undirected Graph", "Medium"),
    (2, "2360. Longest Cycle in a Graph", "Medium"),
    (2, "2368. Reachable Nodes With Restrictions", "Medium"),
    (3, "269. Alien Dictionary", "Hard"),
    (3, "444. Sequence Reconstruction", "Hard"),
    (3, "685. Redundant Connection II", "Hard"),
    (3, "765. Couples Holding Hands", "Hard"),
    (3, "839. Similar String Groups", "Hard"),
    (3, "847. Shortest Path Visiting All Nodes", "Hard"),
    (3, "854. K-Similar Strings", "Hard"),
    (3, "882. Reachable Nodes In Subdivided Graph", "Hard"),
    (3, "924. Minimize Malware Spread", "Hard"),
    (3, "928. Minimize Malware Spread II", "Hard"),
    (3, "1135. Connecting Cities With Minimum Cost", "Hard"),
    (3, "1192. Critical Connections in a Network", "Hard"),
    (3, "1203. Sort Items by Groups Respecting Dependencies", "Hard"),
    (3, "1298. Maximum Candies You Can Get from Boxes", "Hard"),
    (3, "1368. Minimum Cost to Make at Least One Valid Path in a Grid", "Hard"),
    (3, "1489. Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree", "Hard"),
    (3, "1786. Number of Restricted Paths From First to Last Node", "Hard"),
    (3, "1857. Largest Color Value in a Directed Graph", "Hard"),
    (3, "1976. Number of Ways to Arrive at Destination", "Hard"),
    (3, "2092. Find All People With Secret", "Hard"),
    (3, "2421. Number of Good Paths", "Hard")
]
