graph_problems = [
    "133. Clone Graph",
    "200. Number of Islands",
    "207. Course Schedule",
    "210. Course Schedule II",
    "261. Graph Valid Tree",
    "269. Alien Dictionary",
    "310. Minimum Height Trees",
    "323. Number of Connected Components in an Undirected Graph",
    "332. Reconstruct Itinerary",
    "399. Evaluate Division",
    "417. Pacific Atlantic Water Flow",
    "433. Minimum Genetic Mutation",
    "444. Sequence Reconstruction",
    "547. Number of Provinces",
    "684. Redundant Connection",
    "685. Redundant Connection II",
    "743. Network Delay Time",
    "765. Couples Holding Hands",
    "785. Is Graph Bipartite?",
    "787. Cheapest Flights Within K Stops",
    "797. All Paths From Source to Target",
    "802. Find Eventual Safe States",
    "839. Similar String Groups",
    "841. Keys and Rooms",
    "847. Shortest Path Visiting All Nodes",
    "851. Loud and Rich",
    "854. K-Similar Strings",
    "882. Reachable Nodes In Subdivided Graph",
    "886. Possible Bipartition",
    "924. Minimize Malware Spread",
    "928. Minimize Malware Spread II",
    "934. Shortest Bridge",
    "947. Most Stones Removed with Same Row or Column",
    "959. Regions Cut By Slashes",
    "990. Satisfiability of Equality Equations",
    "997. Find the Town Judge",
    "1020. Number of Enclaves",
    "1042. Flower Planting With No Adjacent",
    "1135. Connecting Cities With Minimum Cost",
    "1162. As Far from Land as Possible",
    "1192. Critical Connections in a Network",
    "1202. Smallest String With Swaps",
    "1203. Sort Items by Groups Respecting Dependencies",
    "1254. Number of Closed Islands",
    "1267. Count Servers that Communicate",
    "1298. Maximum Candies You Can Get from Boxes",
    "1319. Number of Operations to Make Network Connected",
    "1334. Find the City With the Smallest Number of Neighbors at a Threshold Distance",
    "1361. Validate Binary Tree Nodes",
    "1368. Minimum Cost to Make at Least One Valid Path in a Grid",
    "1391. Check if There is a Valid Path in a Grid",
    "1436. Destination City",
    "1462. Course Schedule IV",
    "1466. Reorder Routes to Make All Paths Lead to the City Zero",
    "1489. Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree",
    "1514. Path with Maximum Probability",
    "1519. Number of Nodes in the Sub-Tree With the Same Label",
    "1557. Minimum Number of Vertices to Reach All Nodes",
    "1584. Min Cost to Connect All Points",
    "1615. Maximal Network Rank",
    "1627. Graph Connectivity With Threshold",
    "1631. Path With Minimum Effort",
    "1786. Number of Restricted Paths From First to Last Node",
    "1791. Find Center of Star Graph",
    "1857. Largest Color Value in a Directed Graph",
    "1926. Nearest Exit from Entrance in Maze",
    "1976. Number of Ways to Arrive at Destination",
    "2039. The Time When the Network Becomes Idle",
    "2065. Maximum Path Quality of a Graph",
    "2092. Find All People With Secret",
    "2115. Find All Possible Recipes from Given Supplies",
    "2192. All Ancestors of a Node in a Directed Acyclic Graph",
    "2246. Longest Path With Different Adjacent Characters",
    "2285. Maximum Total Importance of Roads",
    "2316. Count Unreachable Pairs of Nodes in an Undirected Graph",
    "2360. Longest Cycle in a Graph",
    "2368. Reachable Nodes With Restrictions",
    "2421. Number of Good Paths"
]
