greedy_problems = [
    "11. Container With Most Water",
    "45. Jump Game II",
    "55. Jump Game",
    "122. Best Time to Buy and Sell Stock II",
    "134. Gas Station",
    "135. Candy",
    "179. Largest Number",
    "253. Meeting Rooms II",
    "316. Remove Duplicate Letters",
    "321. Create Maximum Number",
    "330. Patching Array",
    "376. Wiggle Subsequence",
    "392. Is Subsequence",
    "402. Remove K Digits",
    "406. Queue Reconstruction by Height",
    "435. Non-overlapping Intervals",
    "452. Minimum Number of Arrows to Burst Balloons",
    "455. Assign Cookies",
    "484. Find Permutation",
    "502. IPO",
    "621. Task Scheduler",
    "630. Course Schedule III",
    "646. Maximum Length of Pair Chain",
    "659. Split Array into Consecutive Subsequences",
    "714. Best Time to Buy and Sell Stock with Transaction Fee",
    "738. Monotone Increasing Digits",
    "757. Set Intersection Size At Least Two",
    "759. Employee Free Time",
    "763. Partition Labels",
    "767. Reorganize String",
    "861. Score After Flipping Matrix",
    "870. Advantage Shuffle",
    "881. Boats to Save People",
    "921. Minimum Add to Make Parentheses Valid",
    "942. DI String Match",
    "944. Delete Columns to Make Sorted",
    "955. Delete Columns to Make Sorted II",
    "984. String Without AAA or BBB",
    "991. Broken Calculator",
    "1005. Maximize Sum Of Array After K Negations",
    "1029. Two City Scheduling",
    "1046. Last Stone Weight",
    "1094. Car Pooling",
    "1111. Maximum Nesting Depth of Two Valid Parentheses Strings",
    "1196. How Many Apples Can You Put into the Basket",
    "1217. Minimum Cost to Move Chips to The Same Position",
    "1221. Split a String in Balanced Strings",
    "1247. Minimum Swaps to Make Strings Equal",
    "1249. Minimum Remove to Make Valid Parentheses",
    "1282. Group the People Given the Group Size They Belong To",
    "1326. Minimum Number of Taps to Open to Water a Garden",
    "1338. Reduce Array Size to The Half",
    "1353. Maximum Number of Events That Can Be Attended",
    "1383. Maximum Performance of a Team",
    "1400. Construct K Palindrome Strings",
    "1405. Longest Happy String",
    "1414. Find the Minimum Number of Fibonacci Numbers Whose Sum Is K",
    "1433. Check If a String Can Break Another String",
    "1481. Least Number of Unique Integers after K Removals",
    "1497. Check If Array Pairs Are Divisible by k",
    "1518. Water Bottles",
    "1520. Maximum Number of Non-Overlapping Substrings",
    "1540. Can Convert String in K Moves",
    "1558. Minimum Numbers of Function Calls to Make Target Array",
    "1605. Find Valid Matrix Given Row and Column Sums",
    "1647. Minimum Deletions to Make Character Frequencies Unique",
    "1663. Smallest String With A Given Numeric Value",
    "1689. Partitioning Into Minimum Number Of Deci-Binary Numbers",
    "1710. Maximum Units on a Truck",
    "1725. Number Of Rectangles That Can Form The Largest Square",
    "1736. Latest Time by Replacing Hidden Digits",
    "1775. Equal Sum Arrays With Minimum Number of Operations",
    "1798. Maximum Number of Consecutive Values You Can Make",
    "1801. Number of Orders in the Backlog",
    "1827. Minimum Operations to Make the Array Increasing",
    "1834. Single-Threaded CPU",
    "1846. Maximum Element After Decreasing and Rearranging",
    "1877. Minimize Maximum Pair Sum in Array",
    "1899. Merge Triplets to Form Target Triplet",
    "1961. Check If String Is a Prefix of Array",
    "1975. Maximum Matrix Sum",
    "2027. Minimum Moves to Convert String",
    "2029. Stone Game IX",
    "2126. Destroying Asteroids",
    "2139. Minimum Moves to Reach Target Score",
    "2144. Minimum Cost of Buying Candies With Discount",
    "2160. Minimum Sum of Four Digit Number After Splitting Digits",
    "2178. Maximum Split of Positive Even Integers",
    "2202. Maximize the Topmost Element After K Moves",
    "2224. Minimum Number of Operations to Convert Time",
    "2279. Maximum Bags With Full Capacity of Rocks",
    "2294. Partition Array Such That Maximum Difference Is K",
    "2335. Minimum Amount of Time to Fill Cups",
    "2358. Maximum Number of Groups Entering a Competition",
    "2375. Construct Smallest Number From DI String",
    "2434. Using a Robot to Print the Lexicographically Smallest String",
    "2457. Minimum Addition to Make Integer Beautiful",
    "2522. Partition String Into Substrings With Values at Most K",
    "2541. Minimum Operations to Make Array Equal II"
]
