greedy_problems = [
    (1, "455. Assign Cookies", "Easy"),
    (1, "944. Delete Columns to Make Sorted", "Easy"),
    (1, "1005. Maximize Sum Of Array After K Negations", "Easy"),
    (1, "1046. Last Stone Weight", "Easy"),
    (1, "1196. How Many Apples Can You Put into the Basket", "Easy"),
    (1, "1217. Minimum Cost to Move Chips to The Same Position", "Easy"),
    (1, "1221. Split a String in Balanced Strings", "Easy"),
    (1, "1518. Water Bottles", "Easy"),
    (1, "1710. Maximum Units on a Truck", "Easy"),
    (1, "1725. Number Of Rectangles That Can Form The Largest Square", "Easy"),
    (1, "1827. Minimum Operations to Make the Array Increasing", "Easy"),
    (1, "1961. Check If String Is a Prefix of Array", "Easy"),
    (1, "2027. Minimum Moves to Convert String", "Easy"),
    (1, "2144. Minimum Cost of Buying Candies With Discount", "Easy"),
    (1, "2160. Minimum Sum of Four Digit Number After Splitting Digits", "Easy"),
    (1, "2224. Minimum Number of Operations to Convert Time", "Easy"),
    (1, "2335. Minimum Amount of Time to Fill Cups", "Easy"),
    (2, "11. Container With Most Water", "Medium"),
    (2, "45. Jump Game II", "Medium"),
    (2, "55. Jump Game", "Medium"),
    (2, "122. Best Time to Buy and Sell Stock II", "Medium"),
    (2, "134. Gas Station", "Medium"),
    (2, "179. Largest Number", "Medium"),
    (2, "253. Meeting Rooms II", "Medium"),
    (2, "316. Remove Duplicate Letters", "Medium"),
    (2, "376. Wiggle Subsequence", "Medium"),
    (2, "392. Is Subsequence", "Medium"),
    (2, "402. Remove K Digits", "Medium"),
    (2, "406. Queue Reconstruction by Height", "Medium"),
    (2, "435. Non-overlapping Intervals", "Medium"),
    (2, "452. Minimum Number of Arrows to Burst Balloons", "Medium"),
    (2, "484. Find Permutation", "Medium"),
    (2, "621. Task Scheduler", "Medium"),
    (2, "646. Maximum Length of Pair Chain", "Medium"),
    (2, "659. Split Array into Consecutive Subsequences", "Medium"),
    (2, "714. Best Time to Buy and Sell Stock with Transaction Fee", "Medium"),
    (2, "738. Monotone Increasing Digits", "Medium"),
    (2, "763. Partition Labels", "Medium"),
    (2, "767. Reorganize String", "Medium"),
    (2, "861. Score After Flipping Matrix", "Medium"),
    (2, "870. Advantage Shuffle", "Medium"),
    (2, "881. Boats to Save People", "Medium"),
    (2, "921. Minimum Add to Make Parentheses Valid", "Medium"),
    (2, "942. DI String Match", "Medium"),
    (2, "984. String Without AAA or BBB", "Medium"),
    (2, "991. Broken Calculator", "Medium"),
    (2, "1029. Two City Scheduling", "Medium"),
    (2, "1094. Car Pooling", "Medium"),
    (2, "1247. Minimum Swaps to Make Strings Eq
