heap_priority_queue_problems = [
    (1, "703. Kth Largest Element in a Stream", "Easy"),
    (1, "1046. Last Stone Weight", "Easy"),
    (1, "2336. Smallest Number in Infinite Set", "Easy"),
    (2, "215. Kth Largest Element in an Array", "Medium"),
    (2, "347. Top K Frequent Elements", "Medium"),
    (2, "373. Find K Pairs with Smallest Sums", "Medium"),
    (2, "378. Kth Smallest Element in a Sorted Matrix", "Medium"),
    (2, "451. Sort Characters By Frequency", "Medium"),
    (2, "621. Task Scheduler", "Medium"),
    (2, "659. Split Array into Consecutive Subsequences", "Medium"),
    (2, "692. Top K Frequent Words", "Medium"),
    (2, "743. Network Delay Time", "Medium"),
    (2, "767. Reorganize String", "Medium"),
    (2, "787. Cheapest Flights Within K Stops", "Medium"),
    (2, "855. Exam Room", "Medium"),
    (2, "1054. Distant Barcodes", "Medium"),
    (2, "1167. Minimum Cost to Connect Sticks", "Medium"),
    (2, "1642. Furthest Building You Can Reach", "Medium"),
    (2, "1705. Maximum Number of Eaten Apples", "Medium"),
    (2, "1753. Maximum Score From Removing Stones", "Medium"),
    (2, "1801. Number of Orders in the Backlog", "Medium"),
    (2, "1845. Seat Reservation Manager", "Medium"),
    (2, "1882. Process Tasks Using Servers", "Medium"),
    (2, "1942. The Number of the Smallest Unoccupied Chair", "Medium"),
    (2, "2034. Stock Price Fluctuation", "Medium"),
    (2, "2099. Find Subsequence of Length K With the Largest Sum", "Medium"),
    (2, "2146. K Highest Ranked Items Within a Price Range", "Medium"),
    (2, "2208. Minimum Operations to Halve Array Sum", "Medium"),
    (2, "2406. Divide Intervals Into Minimum Number of Groups", "Medium"),
    (2, "2462. Total Cost to Hire K Workers", "Medium"),
    (2, "2542. Maximum Subsequence Score", "Medium"),
    (3, "23. Merge k Sorted Lists", "Hard"),
    (3, "218. The Skyline Problem", "Hard"),
    (3, "239. Sliding Window Maximum", "Hard"),
    (3, "295. Find Median from Data Stream", "Hard"),
    (3, "313. Super Ugly Number", "Hard"),
    (3, "355. Design Twitter", "Hard"),
    (3, "407. Trapping Rain Water II", "Hard"),
    (3, "502. IPO", "Hard"),
    (3, "632. Smallest Range Covering Elements from K Lists", "Hard"),
    (3, "778. Swim in Rising Water", "Hard"),
    (3, "786. K-th Smallest Prime Fraction", "Hard"),
    (3, "818. Race Car", "Hard"),
    (3, "857. Minimum Cost to Hire K Workers", "Hard"),
    (3, "871. Minimum Number of Refueling Stops", "Hard"),
    (3, "882. Reachable Nodes In Subdivided Graph", "Hard"),
    (3, "895. Maximum Frequency Stack", "Hard"),
    (3, "1439. Find the Kth Smallest Sum of a Matrix With Sorted Rows", "Hard"),
    (3, "1675. Minimize Deviation in Array", "Hard"),
    (3, "2102. Sequentially Ordinal Rank Tracker", "Hard"),
    (3, "2402. Meeting Rooms III", "Hard")
]
