heap_priority_queue_problems = [
    "23. Merge k Sorted Lists",
    "215. Kth Largest Element in an Array",
    "218. The Skyline Problem",
    "239. Sliding Window Maximum",
    "295. Find Median from Data Stream",
    "313. Super Ugly Number",
    "347. Top K Frequent Elements",
    "355. Design Twitter",
    "373. Find K Pairs with Smallest Sums",
    "378. Kth Smallest Element in a Sorted Matrix",
    "407. Trapping Rain Water II",
    "451. Sort Characters By Frequency",
    "502. IPO",
    "621. Task Scheduler",
    "632. Smallest Range Covering Elements from K Lists",
    "659. Split Array into Consecutive Subsequences",
    "692. Top K Frequent Words",
    "703. Kth Largest Element in a Stream",
    "743. Network Delay Time",
    "767. Reorganize String",
    "778. Swim in Rising Water",
    "786. K-th Smallest Prime Fraction",
    "787. Cheapest Flights Within K Stops",
    "818. Race Car",
    "855. Exam Room",
    "857. Minimum Cost to Hire K Workers",
    "871. Minimum Number of Refueling Stops",
    "882. Reachable Nodes In Subdivided Graph",
    "895. Maximum Frequency Stack",
    "1046. Last Stone Weight",
    "1054. Distant Barcodes",
    "1167. Minimum Cost to Connect Sticks",
    "1439. Find the Kth Smallest Sum of a Matrix With Sorted Rows",
    "1642. Furthest Building You Can Reach",
    "1675. Minimize Deviation in Array",
    "1705. Maximum Number of Eaten Apples",
    "1753. Maximum Score From Removing Stones",
    "1801. Number of Orders in the Backlog",
    "1845. Seat Reservation Manager",
    "1882. Process Tasks Using Servers",
    "1942. The Number of the Smallest Unoccupied Chair",
    "2034. Stock Price Fluctuation",
    "2099. Find Subsequence of Length K With the Largest Sum",
    "2102. Sequentially Ordinal Rank Tracker",
    "2146. K Highest Ranked Items Within a Price Range",
    "2208. Minimum Operations to Halve Array Sum",
    "2336. Smallest Number in Infinite Set",
    "2402. Meeting Rooms III",
    "2406. Divide Intervals Into Minimum Number of Groups",
    "2462. Total Cost to Hire K Workers",
    "2542. Maximum Subsequence Score"
]
