interval_problems = [
    "56. Merge Intervals",
    "57. Insert Interval",
    "163. Missing Ranges",
    "228. Summary Ranges",
    "252. Meeting Rooms",
    "253. Meeting Rooms II",
    "352. Data Stream as Disjoint Intervals",
    "370. Range Addition",
    "435. Non-overlapping Intervals",
    "436. Find Right Interval",
    "452. Minimum Number of Arrows to Burst Balloons",
    "495. Teemo Attacking",
    "616. Add Bold Tag in String",
    "646. Maximum Length of Pair Chain",
    "699. Falling Squares",
    "729. My Calendar I",
    "731. My Calendar II",
    "732. My Calendar III",
    "759. Employee Free Time",
    "763. Partition Labels",
    "986. Interval List Intersections",
    "1024. Video Stitching",
    "1094. Car Pooling",
    "1109. Corporate Flight Bookings",
    "1229. Meeting Scheduler",
    "1235. Maximum Profit in Job Scheduling",
    "1272. Remove Interval",
    "1288. Remove Covered Intervals",
    "1326. Minimum Number of Taps to Open to Water a Garden",
    "1520. Maximum Number of Non-Overlapping Substrings",
    "1589. Maximum Sum Obtained of Any Permutation",
    "1674. Minimum Moves to Make Array Complementary",
    "1751. Maximum Number of Events That Can Be Attended II",
    "1798. Maximum Number of Consecutive Values You Can Make",
    "1851. Minimum Interval to Include Each Query",
    "1854. Maximum Population Year",
    "1893. Check if All the Intervals Cover the Range",
    "1943. Describe the Painting",
    "1942. The Number of the Smallest Unoccupied Chair",
    "2158. Amount of New Area Painted Each Day",
    "2406. Divide Intervals Into Minimum Number of Groups",
    "2276. Count Integers in Intervals"
]
