interval_problems = [
    (1, "163. Missing Ranges", "Easy"),
    (1, "228. Summary Ranges", "Easy"),
    (1, "252. Meeting Rooms", "Easy"),
    (1, "495. Teemo Attacking", "Easy"),
    (1, "1854. Maximum Population Year", "Easy"),
    (1, "1893. Check if All the Intervals Cover the Range", "Easy"),
    (2, "56. Merge Intervals", "Medium"),
    (2, "57. Insert Interval", "Medium"),
    (2, "253. Meeting Rooms II", "Medium"),
    (2, "370. Range Addition", "Medium"),
    (2, "435. Non-overlapping Intervals", "Medium"),
    (2, "436. Find Right Interval", "Medium"),
    (2, "452. Minimum Number of Arrows to Burst Balloons", "Medium"),
    (2, "616. Add Bold Tag in String", "Medium"),
    (2, "646. Maximum Length of Pair Chain", "Medium"),
    (2, "729. My Calendar I", "Medium"),
    (2, "731. My Calendar II", "Medium"),
    (2, "763. Partition Labels", "Medium"),
    (2, "986. Interval List Intersections", "Medium"),
    (2, "1024. Video Stitching", "Medium"),
    (2, "1094. Car Pooling", "Medium"),
    (2, "1109. Corporate Flight Bookings", "Medium"),
    (2, "1229. Meeting Scheduler", "Medium"),
    (2, "1272. Remove Interval", "Medium"),
    (2, "1288. Remove Covered Intervals", "Medium"),
    (2, "1589. Maximum Sum Obtained of Any Permutation", "Medium"),
    (2, "1674. Minimum Moves to Make Array Complementary", "Medium"),
    (2, "1798. Maximum Number of Consecutive Values You Can Make", "Medium"),
    (2, "1943. Describe the Painting", "Medium"),
    (2, "1942. The Number of the Smallest Unoccupied Chair", "Medium"),
    (2, "2406. Divide Intervals Into Minimum Number of Groups", "Medium"),
    (3, "352. Data Stream as Disjoint Intervals", "Hard"),
    (3, "699. Falling Squares", "Hard"),
    (3, "732. My Calendar III", "Hard"),
    (3, "759. Employee Free Time", "Hard"),
    (3, "1235. Maximum Profit in Job Scheduling", "Hard"),
    (3, "1326. Minimum Number of Taps to Open to Water a Garden", "Hard"),
    (3, "1520. Maximum Number of Non-Overlapping Substrings", "Hard"),
    (3, "1751. Maximum Number of Events That Can Be Attended II", "Hard"),
    (3, "1851. Minimum Interval to Include Each Query", "Hard"),
    (3, "2158. Amount of New Area Painted Each Day", "Hard"),
    (3, "2276. Count Integers in Intervals", "Hard")
]
