linked_list_problems = [
    "2. Add Two Numbers",
    "19. Remove Nth Node From End of List",
    "21. Merge Two Sorted Lists",
    "23. Merge k Sorted Lists",
    "24. Swap Nodes in Pairs",
    "25. Reverse Nodes in k-Group",
    "61. Rotate List",
    "82. Remove Duplicates from Sorted List II",
    "83. Remove Duplicates from Sorted List",
    "86. Partition List",
    "92. Reverse Linked List II",
    "109. Convert Sorted List to Binary Search Tree",
    "138. Copy List with Random Pointer",
    "141. Linked List Cycle",
    "142. Linked List Cycle II",
    "143. Reorder List",
    "147. Insertion Sort List",
    "148. Sort List",
    "160. Intersection of Two Linked Lists",
    "203. Remove Linked List Elements",
    "206. Reverse Linked List",
    "234. Palindrome Linked List",
    "237. Delete Node in a Linked List",
    "328. Odd Even Linked List",
    "369. Plus One Linked List",
    "382. Linked List Random Node",
    "430. Flatten a Multilevel Doubly Linked List",
    "445. Add Two Numbers II",
    "707. Design Linked List",
    "725. Split Linked List in Parts",
    "817. Linked List Components",
    "876. Middle of the Linked List",
    "1019. Next Greater Node In Linked List",
    "1171. Remove Zero Sum Consecutive Nodes from Linked List",
    "1290. Convert Binary Number in a Linked List to Integer",
    "1669. Merge In Between Linked Lists",
    "1721. Swapping Nodes in a Linked List",
    "1836. Remove Duplicates From an Unsorted Linked List",
    "2058. Find the Minimum and Maximum Number of Nodes Between Critical Points",
    "2095. Delete the Middle Node of a Linked List",
    "2130. Maximum Twin Sum of a Linked List"
]
