linked_list_problems = [
    (1, "21. Merge Two Sorted Lists", "Easy"),
    (1, "83. Remove Duplicates from Sorted List", "Easy"),
    (1, "141. Linked List Cycle", "Easy"),
    (1, "160. Intersection of Two Linked Lists", "Easy"),
    (1, "203. Remove Linked List Elements", "Easy"),
    (1, "206. Reverse Linked List", "Easy"),
    (1, "234. Palindrome Linked List", "Easy"),
    (1, "237. Delete Node in a Linked List", "Easy"),
    (1, "876. Middle of the Linked List", "Easy"),
    (1, "1290. Convert Binary Number in a Linked List to Integer", "Easy"),
    (2, "2. Add Two Numbers", "Medium"),
    (2, "19. Remove Nth Node From End of List", "Medium"),
    (2, "24. Swap Nodes in Pairs", "Medium"),
    (2, "61. Rotate List", "Medium"),
    (2, "82. Remove Duplicates from Sorted List II", "Medium"),
    (2, "86. Partition List", "Medium"),
    (2, "92. Reverse Linked List II", "Medium"),
    (2, "109. Convert Sorted List to Binary Search Tree", "Medium"),
    (2, "138. Copy List with Random Pointer", "Medium"),
    (2, "142. Linked List Cycle II", "Medium"),
    (2, "143. Reorder List", "Medium"),
    (2, "147. Insertion Sort List", "Medium"),
    (2, "148. Sort List", "Medium"),
    (2, "328. Odd Even Linked List", "Medium"),
    (2, "369. Plus One Linked List", "Medium"),
    (2, "382. Linked List Random Node", "Medium"),
    (2, "430. Flatten a Multilevel Doubly Linked List", "Medium"),
    (2, "445. Add Two Numbers II", "Medium"),
    (2, "707. Design Linked List", "Medium"),
    (2, "725. Split Linked List in Parts", "Medium"),
    (2, "817. Linked List Components", "Medium"),
    (2, "1019. Next Greater Node In Linked List", "Medium"),
    (2, "1171. Remove Zero Sum Consecutive Nodes from Linked List", "Medium"),
    (2, "1669. Merge In Between Linked Lists", "Medium"),
    (2, "1721. Swapping Nodes in a Linked List", "Medium"),
    (2, "2058. Find the Minimum and Maximum Number of Nodes Between Critical Points", "Medium"),
    (2, "2095. Delete the Middle Node of a Linked List", "Medium"),
    (2, "2130. Maximum Twin Sum of a Linked List", "Medium"),
    (3, "23. Merge k Sorted Lists", "Hard"),
    (3, "25. Reverse Nodes in k-Group", "Hard"),
    (3, "1836. Remove Duplicates From an Unsorted Linked List", "Hard")
]
