math_and_geometry_problems = [
    (1, "7. Reverse Integer", "Easy"),
    (1, "9. Palindrome Number", "Easy"),
    (1, "13. Roman to Integer", "Easy"),
    (1, "66. Plus One", "Easy"),
    (1, "67. Add Binary", "Easy"),
    (1, "69. Sqrt(x)", "Easy"),
    (1, "168. Excel Sheet Column Title", "Easy"),
    (1, "171. Excel Sheet Column Number", "Easy"),
    (1, "202. Happy Number", "Easy"),
    (1, "231. Power of Two", "Easy"),
    (1, "258. Add Digits", "Easy"),
    (1, "263. Ugly Number", "Easy"),
    (1, "268. Missing Number", "Easy"),
    (1, "326. Power of Three", "Easy"),
    (1, "342. Power of Four", "Easy"),
    (1, "367. Valid Perfect Square", "Easy"),
    (1, "412. Fizz Buzz", "Easy"),
    (1, "415. Add Strings", "Easy"),
    (1, "441. Arranging Coins", "Easy"),
    (1, "453. Minimum Moves to Equal Array Elements", "Easy"),
    (1, "492. Construct the Rectangle", "Easy"),
    (1, "507. Perfect Number", "Easy"),
    (1, "598. Range Addition II", "Easy"),
    (1, "628. Maximum Product of Three Numbers", "Easy"),
    (1, "633. Sum of Square Numbers", "Easy"),
    (1, "645. Set Mismatch", "Easy"),
    (1, "728. Self Dividing Numbers", "Easy"),
    (1, "812. Largest Triangle Area", "Easy"),
    (1, "836. Rectangle Overlap", "Easy"),
    (1, "883. Projection Area of 3D Shapes", "Easy"),
    (1, "892. Surface Area of 3D Shapes", "Easy"),
    (1, "908. Smallest Range I", "Easy"),
    (1, "914. X of a Kind in a Deck of Cards", "Easy"),
    (1, "942. DI String Match", "Easy"),
    (1, "949. Largest Time for Given Digits", "Easy"),
    (1, "976. Largest Perimeter Triangle", "Easy"),
    (1, "1025. Divisor Game", "Easy"),
    (1, "1037. Valid Boomerang", "Easy"),
    (1, "1056. Confusing Number", "Easy"),
    (1, "1103. Distribute Candies to People", "Easy"),
    (1, "1137. N-th Tribonacci Number", "Easy"),
    (1, "1154. Day of the Year", "Easy"),
    (1, "1185. Day of the Week", "Easy"),
    (1, "1217. Minimum Cost to Move Chips to The Same Position", "Easy"),
    (1, "1232. Check If It Is a Straight Line", "Easy"),
    (1, "1266. Minimum Time Visiting All Points", "Easy"),
    (1, "1281. Subtract the Product and Sum of Digits of an Integer", "Easy"),
    (1, "1317. Convert Integer to the Sum of Two No-Zero Integers", "Easy"),
    (1, "1323. Maximum 69 Number", "Easy"),
    (1, "1360. Number of Days Between Two Dates", "Easy"),
    (1, "1399. Count Largest Group", "Easy"),
    (1, "1450. Number of Students Doing Homework at a Given Time", "Easy"),
    (1, "1518. Water Bottles", "Easy"),
    (1, "1523. Count Odd Numbers in an Interval Range", "Easy"),
    (1, "1556. Thousand Separator", "Easy"),
    (1, "1688. Count of Matches in Tournament", "Easy"),
    (1, "1716. Calculate Money in Leetcode Bank", "Easy"),
    (1, "1837. Sum of Digits in Base K", "Easy"),
    (1, "1925. Count Square Sum Triples", "Easy"),
    (1, "1979. Find Greatest Common Divisor of Array", "Easy"),
    (1, "2413. Smallest Even Multiple", "Easy"),
    (1, "2427. Number of Common Factors", "Easy"),
    (1, "2469. Convert the Temperature", "Easy"),
    (1, "2485. Find the Pivot Integer", "Easy"),
    (1, "2549. Count Distinct Numbers on Board", "Easy"),
    (2, "12. Integer to Roman", "Medium"),
    (2, "29. Divide Two Integers", "Medium"),
    (2, "43. Multiply Strings", "Medium"),
    (2, "48. Rotate Image", "Medium"),
    (2, "50. Pow(x, n)", "Medium"),
    (2, "60. Permutation Sequence", "Medium"),
    (2, "166. Fraction to Recurr
