math_and_geometry_problems = [
    "7. Reverse Integer",
    "9. Palindrome Number",
    "12. Integer to Roman",
    "13. Roman to Integer",
    "29. Divide Two Integers",
    "43. Multiply Strings",
    "48. Rotate Image",
    "50. Pow(x, n)",
    "60. Permutation Sequence",
    "65. Valid Number",
    "66. Plus One",
    "67. Add Binary",
    "69. Sqrt(x)",
    "149. Max Points on a Line",
    "166. Fraction to Recurring Decimal",
    "168. Excel Sheet Column Title",
    "171. Excel Sheet Column Number",
    "172. Factorial Trailing Zeroes",
    "202. Happy Number",
    "204. Count Primes",
    "223. Rectangle Area",
    "224. Basic Calculator",
    "231. Power of Two",
    "233. Number of Digit One",
    "246. Strobogrammatic Number",
    "247. Strobogrammatic Number II",
    "248. Strobogrammatic Number III",
    "258. Add Digits",
    "263. Ugly Number",
    "264. Ugly Number II",
    "268. Missing Number",
    "273. Integer to English Words",
    "279. Perfect Squares",
    "296. Best Meeting Point",
    "313. Super Ugly Number",
    "319. Bulb Switcher",
    "326. Power of Three",
    "342. Power of Four",
    "343. Integer Break",
    "356. Line Reflection",
    "357. Count Numbers with Unique Digits",
    "360. Sort Transformed Array",
    "365. Water and Jug Problem",
    "367. Valid Perfect Square",
    "372. Super Pow",
    "396. Rotate Function",
    "400. Nth Digit",
    "412. Fizz Buzz",
    "413. Arithmetic Slices",
    "415. Add Strings",
    "423. Reconstruct Original Digits from English",
    "441. Arranging Coins",
    "453. Minimum Moves to Equal Array Elements",
    "462. Minimum Moves to Equal Array Elements II",
    "469. Convex Polygon",
    "478. Generate Random Point in a Circle",
    "483. Smallest Good Base",
    "492. Construct the Rectangle",
    "507. Perfect Number",
    "517. Super Washing Machines",
    "537. Complex Number Multiplication",
    "553. Optimal Division",
    "593. Valid Square",
    "598. Range Addition II",
    "625. Minimum Factorization",
    "628. Maximum Product of Three Numbers",
    "633. Sum of Square Numbers",
    "640. Solve the Equation",
    "645. Set Mismatch",
    "670. Maximum Swap",
    "672. Bulb Switcher II",
    "728. Self Dividing Numbers",
    "754. Reach a Number",
    "775. Global and Local Inversions",
    "780. Reaching Points",
    "781. Rabbits in Forest",
    "789. Escape The Ghosts",
    "794. Valid Tic-Tac-Toe State",
    "810. Chalkboard XOR Game",
    "812. Largest Triangle Area",
    "829. Consecutive Numbers Sum",
    "836. Rectangle Overlap",
    "858. Mirror Reflection",
    "866. Prime Palindrome",
    "869. Reordered Power of 2",
    "878. Nth Magical Number",
    "883. Projection Area of 3D Shapes",
    "885. Spiral Matrix III",
    "887. Super Egg Drop",
    "891. Sum of Subsequence Widths",
    "892. Surface Area of 3D Shapes",
    "902. Numbers At Most N Given Digit Set",
    "906. Super Palindromes",
    "908. Smallest Range I",
    "910. Smallest Range II",
    "914. X of a Kind in a Deck of Cards",
    "927. Three Equal Parts",
    "942. DI String Match",
    "949. Largest Time for Given Digits",
    "952. Largest Component Size by Common Factor",
    "963. Minimum Area Rectangle II",
    "970. Powerful Integers",
    "972. Equal Rational Numbers",
    "976. Largest Perimeter Triangle",
    "991. Broken Calculator",
    "996. Number of Squareful Arrays",
    "1006. Clumsy Factorial",
    "1012. Numbers With Repeated Digits",
    "1015. Smallest Integer Divisible by K",
    "1017. Convert to Base -2",
    "1025. Divisor Game",
    "1037. Valid Boomerang",
    "1041. Robot Bounded In Circle",
    "1056. Confusing Number",
    "1073. Adding Two Negabinary Numbers",
    "1088. Confusing Number II",
    "1093. Statistics from a Large Sample",
    "1103. Distribute Candies to People",
    "1104. Path In Zigzag Labelled Binary Tree",
    "1131. Maximum of Absolute Value Expression",
    "1137. N-th Tribonacci Number",
    "1154. Day of the Year",
    "1175. Prime Arrangements",
    "1185. Day of the Week",
    "1201. Ugly Number III",
    "1217. Minimum Cost to Move Chips to The Same Position",
    "1220. Count Vowels Permutation",
    "1232. Check If It Is a Straight Line",
    "1237. Find Positive Integer Solution for a Given Equation",
    "1238. Circular Permutation in Binary Representation",
    "1250. Check If It Is a Good Array",
    "1259. Handshakes That Don't Cross",
    "1266. Minimum Time Visiting All Points",
    "1281. Subtract the Product and Sum of Digits of an Integer",
    "1317. Convert Integer to the Sum of Two No-Zero Integers",
    "1323. Maximum 69 Number",
    "1344. Angle Between Hands of a Clock",
    "1360. Number of Days Between Two Dates",
    "1362. Closest Divisors",
    "1390. Four Divisors",
    "1399. Count Largest Group",
    "1401. Circle and Rectangle Overlapping",
    "1414. Find the Minimum Number of Fibonacci Numbers Whose Sum Is K",
    "1447. Simplified Fractions",
    "1450. Number of Students Doing Homework at a Given Time",
    "1492. The kth Factor of n",
    "1497. Check If Array Pairs Are Divisible by k",
    "1513. Number of Substrings With Only 1s",
    "1518. Water Bottles",
    "1523. Count Odd Numbers in an Interval Range",
    "1551. Minimum Operations to Make Array Equal",
    "1556. Thousand Separator",
    "1573. Number of Ways to Split a String",
    "1611. Minimum One Bit Operations to Make Integers Zero",
    "1622. Fancy Sequence",
    "1648. Sell Diminishing-Valued Colored Balls",
    "1680. Concatenation of Consecutive Binary Numbers",
    "1688. Count of Matches in Tournament",
    "1716. Calculate Money in Leetcode Bank",
    "1735. Count Ways to Make Array With Product",
    "1739. Building Boxes",
    "1753. Maximum Score From Removing Stones",
    "1780. Check if Number is a Sum of Powers of Three",
    "1799. Maximize Score After N Operations",
    "1814. Count Nice Pairs in an Array",
    "1823. Find the Winner of the Circular Game",
    "1837. Sum of Digits in Base K",
    "1862. Sum of Floored Pairs",
    "1878. Get Biggest Three Rhombus Sums in a Grid",
    "1904. The Number of Full Rounds You Have Played",
    "1915. Number of Wonderful Substrings",
    "1922. Count Good Numbers",
    "1925. Count Square Sum Triples",
    "1954. Minimum Garden Perimeter to Collect Enough Apples",
    "1969. Minimum Non-Zero Product of the Array Elements",
    "1979. Find Greatest Common Divisor of Array",
    "1998. GCD Sort of an Array",
    "2001. Number of Pairs of Interchangeable Rectangles",
    "2013. Detect Squares",
    "2028. Find Missing Observations",
    "2049. Count Nodes With the Highest Score",
    "2063. Vowels of All Substrings",
    "2064. Minimized Maximum of Products Distributed to Any Store",
    "2183. Count Array Pairs Divisible by K",
    "2186. Minimum Number of Steps to Make Two Strings Anagram II",
    "2195. Append K Integers With Minimal Sum",
    "2217. Find Palindrome With Fixed Length",
    "2249. Count Lattice Points Inside a Circle",
    "2280. Minimum Lines to Represent a Line Chart",
    "2310. Sum of Numbers With Units Digit K",
    "2316. Count Unreachable Pairs of Nodes in an Undirected Graph",
    "2335. Minimum Amount of Time to Fill Cups",
    "2344. Minimum Deletions to Make Array Divisible",
    "2396. Strictly Palindromic Number",
    "2413. Smallest Even Multiple",
    "2427. Number of Common Factors",
    "2447. Number of Subarrays With GCD Equal to K",
    "2469. Convert the Temperature",
    "2485. Find the Pivot Integer",
    "2492. Minimum Score of a Path Between Two Cities",
    "2521. Distinct Prime Factors of Product of Array",
    "2523. Closest Prime Numbers in Range",
    "2549. Count Distinct Numbers on Board",
    "2550. Count Collisions of Monkeys on a Polygon"
]
