one_d_dp_problems = [
    "5. Longest Palindromic Substring",
    "53. Maximum Subarray",
    "55. Jump Game",
    "62. Unique Paths",
    "70. Climbing Stairs",
    "91. Decode Ways",
    "95. Unique Binary Search Trees II",
    "96. Unique Binary Search Trees",
    "120. Triangle",
    "121. Best Time to Buy and Sell Stock",
    "122. Best Time to Buy and Sell Stock II",
    "139. Word Break",
    "152. Maximum Product Subarray",
    "198. House Robber",
    "213. House Robber II",
    "256. Paint House",
    "264. Ugly Number II",
    "276. Paint Fence",
    "279. Perfect Squares",
    "300. Longest Increasing Subsequence",
    "309. Best Time to Buy and Sell Stock with Cooldown",
    "322. Coin Change",
    "338. Counting Bits",
    "343. Integer Break",
    "357. Count Numbers with Unique Digits",
    "368. Largest Divisible Subset",
    "376. Wiggle Subsequence",
    "377. Combination Sum IV",
    "392. Is Subsequence",
    "413. Arithmetic Slices",
    "416. Partition Equal Subset Sum",
    "446. Arithmetic Slices II - Subsequence",
    "467. Unique Substrings in Wraparound String",
    "473. Matchsticks to Square",
    "474. Ones and Zeroes",
    "486. Predict the Winner",
    "494. Target Sum",
    "509. Fibonacci Number",
    "516. Longest Palindromic Subsequence",
    "518. Coin Change 2",
    "583. Delete Operation for Two Strings",
    "647. Palindromic Substrings",
    "650. 2 Keys Keyboard",
    "651. 4 Keys Keyboard",
    "673. Number of Longest Increasing Subsequence",
    "688. Knight Probability in Chessboard",
    "714. Best Time to Buy and Sell Stock with Transaction Fee",
    "718. Maximum Length of Repeated Subarray",
    "740. Delete and Earn",
    "746. Min Cost Climbing Stairs",
    "790. Domino and Tromino Tiling",
    "801. Minimum Swaps To Make Sequences Increasing",
    "813. Largest Sum of Averages",
    "838. Push Dominoes",
    "873. Length of Longest Fibonacci Subsequence",
    "877. Stone Game",
    "887. Super Egg Drop",
    "926. Flip String to Monotone Increasing",
    "931. Minimum Falling Path Sum",
    "935. Knight Dialer",
    "983. Minimum Cost For Tickets",
    "1025. Divisor Game",
    "1027. Longest Arithmetic Subsequence",
    "1043. Partition Array for Maximum Sum",
    "1048. Longest String Chain",
    "1105. Filling Bookcase Shelves",
    "1137. N-th Tribonacci Number",
    "1143. Longest Common Subsequence",
    "1191. K-Concatenation Maximum Sum",
    "1218. Longest Arithmetic Subsequence of Given Difference",
    "1235. Maximum Profit in Job Scheduling",
    "1277. Count Square Submatrices with All Ones",
    "1314. Matrix Block Sum",
    "1326. Minimum Number of Taps to Open to Water a Garden",
    "1340. Jump Game V",
    "1359. Count All Valid Pickup and Delivery Options",
    "1388. Pizza With 3n Slices",
    "1402. Reducing Dishes",
    "1416. Restore The Array",
    "1449. Form Largest Integer With Digits That Add up to Target",
    "1458. Max Dot Product of Two Subsequences",
    "1463. Cherry Pickup II",
    "1641. Count Sorted Vowel Strings",
    "1646. Get Maximum in Generated Array",
    "1653. Minimum Deletions to Make String Balanced",
    "1654. Minimum Jumps to Reach Home",
    "1659. Maximize Grid Happiness",
    "1664. Ways to Make a Fair Array",
    "1690. Stone Game VII",
    "1691. Maximum Height by Stacking Cuboids",
    "1696. Jump Game VI",
    "1770. Maximum Score from Performing Multiplication Operations",
    "1884. Egg Drop With 2 Eggs and N Floors",
    "1937. Maximum Number of Points with Cost",
    "2140. Solving Questions With Brainpower",
    "2167. Minimum Time to Remove All Cars Containing Illegal Goods",
    "2222. Number of Ways to Select Buildings",
    "2240. Number of Ways to Buy Pens and Pencils",
    "2266. Count Number of Texts",
    "2320. Count Number of Ways to Place Houses",
    "2327. Number of People Aware of a Secret",
    "2369. Check if There is a Valid Partition For The Array",
    "2370. Longest Ideal Subsequence",
    "2400. Number of Ways to Reach a Position After Exactly k Steps",
    "2466. Count Ways To Build Good Strings",
    "2533. Number of Good Binary Strings"
]
