math_and_geometry_problems = [
    (1, "7. Reverse Integer", "Easy"),
    (1, "9. Palindrome Number", "Easy"),
    (1, "13. Roman to Integer", "Easy"),
    (1, "66. Plus One", "Easy"),
    (1, "67. Add Binary", "Easy"),
    (1, "69. Sqrt(x)", "Easy"),
    (1, "168. Excel Sheet Column Title", "Easy"),
    (1, "171. Excel Sheet Column Number", "Easy"),
    (1, "202. Happy Number", "Easy"),
    (1, "231. Power of Two", "Easy"),
    (1, "258. Add Digits", "Easy"),
    (1, "263. Ugly Number", "Easy"),
    (1, "268. Missing Number", "Easy"),
    (1, "326. Power of Three", "Easy"),
    (1, "342. Power of Four", "Easy"),
    (1, "367. Valid Perfect Square", "Easy"),
    (1, "412. Fizz Buzz", "Easy"),
    (1, "415. Add Strings", "Easy"),
    (1, "441. Arranging Coins", "Easy"),
    (1, "453. Minimum Moves to Equal Array Elements", "Easy"),
    (1, "492. Construct the Rectangle", "Easy"),
    (1, "507. Perfect Number", "Easy"),
    (1, "598. Range Addition II", "Easy"),
    (1, "628. Maximum Product of Three Numbers", "Easy"),
    (1, "633. Sum of Square Numbers", "Easy"),
    (1, "645. Set Mismatch", "Easy"),
    (1, "728. Self Dividing Numbers", "Easy"),
    (1, "812. Largest Triangle Area", "Easy"),
    (1, "836. Rectangle Overlap", "Easy"),
    (1, "883. Projection Area of 3D Shapes", "Easy"),
    (1, "892. Surface Area of 3D Shapes", "Easy"),
    (1, "908. Smallest Range I", "Easy"),
    (1, "914. X of a Kind in a Deck of Cards", "Easy"),
    (1, "942. DI String Match", "Easy"),
    (1, "949. Largest Time for Given Digits", "Easy"),
    (1, "976. Largest Perimeter Triangle", "Easy"),
    (1, "1025. Divisor Game", "Easy"),
    (1, "1037. Valid Boomerang", "Easy"),
    (1, "1056. Confusing Number", "Easy"),
    (1, "1103. Distribute Candies to People", "Easy"),
    (1, "1137. N-th Tribonacci Number", "Easy"),
    (1, "1154. Day of the Year", "Easy"),
    (1, "1185. Day of the Week", "Easy"),
    (1, "1217. Minimum Cost to Move Chips to The Same Position", "Easy"),
    (1, "1232. Check If It Is a Straight Line", "Easy"),
    (1, "1266. Minimum Time Visiting All Points", "Easy"),
    (1, "1281. Subtract the Product and Sum of Digits of an Integer", "Easy"),
    (1, "1317. Convert Integer to the Sum of Two No-Zero Integers", "Easy"),
    (1, "1323. Maximum 69 Number", "Easy"),
    (1, "1360. Number of Days Between Two Dates", "Easy"),
    (1, "1399. Count Largest Group", "Easy"),
    (1, "1450. Number of Students Doing Homework at a Given Time", "Easy"),
    (1, "1518. Water Bottles", "Easy"),
    (1, "1523. Count Odd Numbers in an Interval Range", "Easy"),
    (1, "1556. Thousand Separator", "Easy"),
    (1, "1688. Count of Matches in Tournament", "Easy"),
    (1, "1716. Calculate Money in Leetcode Bank", "Easy"),
    (1, "1837. Sum of Digits in Base K", "Easy"),
    (1, "1925. Count Square Sum Triples", "Easy"),
    (1, "1979. Find Greatest Common Divisor of Array", "Easy"),
    (1, "2413. Smallest Even Multiple", "Easy"),
    (1, "2427. Number of Common Factors", "Easy"),
    (1, "2469. Convert the Temperature", "Easy"),
    (1, "2485. Find the Pivot Integer", "Easy"),
    (1, "2549. Count Distinct Numbers on Board", "Easy"),
    (2, "12. Integer to Roman", "Medium"),
    (2, "29. Divide Two Integers", "Medium"),
    (2, "43. Multiply Strings", "Medium"),
    (2, "48. Rotate Image", "Medium"),
    (2, "50. Pow(x, n)", "Medium"),
    (2, "60. Permutation Sequence", "Medium"),
    (2, "166. Fraction to Recurring Decimal", "Medium"),
    (2, "172. Factorial Trailing Zeroes", "Medium"),
    (2, "204. Count Primes", "Medium"),
    (2, "223. Rectangle Area", "Medium"),
    (2, "264. Ugly Number II", "Medium"),
    (2, "279. Perfect Squares", "Medium"),
    (2, "319. Bulb Switcher", "Medium"),
    (2, "343. Integer Break", "Medium"),
    (2, "357. Count Numbers with Unique Digits", "Medium"),
    (2, "360. Sort Transformed Array", "Medium"),
    (2, "365. Water and Jug Problem", "Medium"),
    (2, "372. Super Pow", "Medium"),
    (2, "396. Rotate Function", "Medium"),
    (2, "400. Nth Digit", "Medium"),
    (2, "413. Arithmetic Slices", "Medium"),
    (2, "423. Reconstruct Original Digits from English", "Medium"),
    (2, "462. Minimum Moves to Equal Array Elements II", "Medium"),
    (2, "478. Generate Random Point in a Circle", "Medium"),
    (2, "537. Complex Number Multiplication", "Medium"),
    (2, "553. Optimal Division", "Medium"),
    (2, "593. Valid Square", "Medium"),
    (2, "640. Solve the Equation", "Medium"),
    (2, "670. Maximum Swap", "Medium"),
    (2, "672. Bulb Switcher II", "Medium"),
    (2, "754. Reach a Number", "Medium"),
    (2, "775. Global and Local Inversions", "Medium"),
    (2, "781. Rabbits in Forest", "Medium"),
    (2, "789. Escape The Ghosts", "Medium"),
    (2, "794. Valid Tic-Tac-Toe State", "Medium"),
    (2, "829. Consecutive Numbers Sum", "Medium"),
    (2, "858. Mirror Reflection", "Medium"),
    (2, "869. Reordered Power of 2", "Medium"),
    (2, "885. Spiral Matrix III", "Medium"),
    (2, "910. Smallest Range II", "Medium"),
    (2, "963. Minimum Area Rectangle II", "Medium"),
    (2, "970. Powerful Integers", "Medium"),
    (2, "991. Broken Calculator", "Medium"),
    (2, "1006. Clumsy Factorial", "Medium"),
    (2, "1015. Smallest Integer Divisible by K", "Medium"),
    (2, "1017. Convert to Base -2", "Medium"),
    (2, "1041. Robot Bounded In Circle", "Medium"),
    (2, "1073. Adding Two Negabinary Numbers", "Medium"),
    (2, "1093. Statistics from a Large Sample", "Medium"),
    (2, "1104. Path In Zigzag Labelled Binary Tree", "Medium"),
    (2, "1131. Maximum of Absolute Value Expression", "Medium"),
    (2, "1175. Prime Arrangements", "Medium"),
    (2, "1238. Circular Permutation in Binary Representation", "Medium"),
    (2, "1344. Angle Between Hands of a Clock", "Medium"),
    (2, "1362. Closest Divisors", "Medium"),
    (2, "1390. Four Divisors", "Medium"),
    (2, "1401. Circle and Rectangle Overlapping", "Medium"),
    (2, "1414. Find the Minimum Number of Fibonacci Numbers Whose Sum Is K", "Medium"),
    (2, "1447. Simplified Fractions", "Medium"),
    (2, "1492. The kth Factor of n", "Medium"),
    (2, "1497. Check If Array Pairs Are Divisible by k", "Medium"),
    (2, "1513. Number of Substrings With Only 1s", "Medium"),
    (2, "1551. Minimum Operations to Make Array Equal", "Medium"),
    (2, "1573. Number of Ways to Split a String", "Medium"),
    (2, "1680. Concatenation of Consecutive Binary Numbers", "Medium"),
    (2, "1753. Maximum Score From Removing Stones", "Medium"),
    (2, "1780. Check if Number is a Sum of Powers of Three", "Medium"),
    (2, "1814. Count Nice Pairs in an Array", "Medium"),
    (2, "1823. Find the Winner of the Circular Game", "Medium"),
    (2, "1878. Get Biggest Three Rhombus Sums in a Grid", "Medium"),
    (2, "1904. The Number of Full Rounds You Have Played", "Medium"),
    (2, "1922. Count Good Numbers", "Medium"),
    (2, "1954. Minimum Garden Perimeter to Collect Enough Apples", "Medium"),
    (2, "2001. Number of Pairs of Interchangeable Rectangles", "Medium"),
    (2, "2013. Detect Squares", "Medium"),
    (2, "2028. Find Missing Observations", "Medium"),
    (2, "2063. Vowels of All Substrings", "Medium"),
    (2, "2064. Minimized Maximum of Products Distributed to Any Store", "Medium"),
    (2, "2186. Minimum Number of Steps to Make Two Strings Anagram II", "Medium"),
    (2, "2195. Append K Integers With Minimal Sum", "Medium"),
    (2, "2249. Count Lattice Points Inside a Circle", "Medium"),
    (2, "2280. Minimum Lines to Represent a Line Chart", "Medium"),
    (2, "2310. Sum of Numbers With Units Digit K", "Medium"),
    (2, "2316. Count Unreachable Pairs of Nodes in an Undirected Graph", "Medium"),
    (2, "2335. Minimum Amount of Time to Fill Cups", "Medium"),
    (2, "2396. Strictly Palindromic Number", "Medium"),
    (2, "2447. Number of Subarrays With GCD Equal to K", "Medium"),
    (2, "2492. Minimum Score of a Path Between Two Cities", "Medium"),
    (2, "2550. Count Collisions of Monkeys on a Polygon", "Medium"),
    (3, "65. Valid Number", "Hard"),
    (3, "149. Max Points on a Line", "Hard"),
    (3, "224. Basic Calculator", "Hard"),
    (3, "233. Number of Digit One", "Hard"),
    (3, "248. Strobogrammatic Number III", "Hard"),
    (3, "273. Integer to English Words", "Hard"),
    (3, "296. Best Meeting Point", "Hard"),
    (3, "313. Super Ugly Number", "Hard"),
    (3, "483. Smallest Good Base", "Hard"),
    (3, "517. Super Washing Machines", "Hard"),
    (3, "780. Reaching Points", "Hard"),
    (3, "810. Chalkboard XOR Game", "Hard"),
    (3, "866. Prime Palindrome", "Hard"),
    (3, "878. Nth Magical Number", "Hard"),
    (3, "887. Super Egg Drop", "Hard"),
    (3, "891. Sum of Subsequence Widths", "Hard"),
    (3, "902. Numbers At Most N Given Digit Set", "Hard"),
    (3, "906. Super Palindromes", "Hard"),
    (3, "927. Three Equal Parts", "Hard"),
    (3, "952. Largest Component Size by Common Factor", "Hard"),
    (3, "972. Equal Rational Numbers", "Hard"),
    (3, "996. Number of Squareful Arrays", "Hard"),
    (3, "1012. Numbers With Repeated Digits", "Hard"),
    (3, "1088. Confusing Number II", "Hard"),
    (3, "1201. Ugly Number III", "Hard"),
    (3, "1220. Count Vowels Permutation", "Hard"),
    (3, "1250. Check If It Is a Good Array", "Hard"),
    (3, "1259. Handshakes That Don't Cross", "Hard"),
    (3, "1611. Minimum One Bit Operations to Make Integers Zero", "Hard"),
    (3, "1622. Fancy Sequence", "Hard"),
    (3, "1648. Sell Diminishing-Valued Colored Balls", "Hard"),
    (3, "1735. Count Ways to Make Array With Product", "Hard"),
    (3, "1739. Building Boxes", "Hard"),
    (3, "1799. Maximize Score After N Operations", "Hard"),
    (3, "1862. Sum of Floored Pairs", "Hard"),
    (3, "1915. Number of Wonderful Substrings", "Hard"),
    (3, "1969. Minimum Non-Zero Product of the Array Elements", "Hard"),
    (3, "1998. GCD Sort of an Array", "Hard"),
    (3, "2049. Count Nodes With the Highest Score", "Hard"),
    (3, "2183. Count Array Pairs Divisible by K", "Hard"),
    (3, "2217. Find Palindrome With Fixed Length", "Hard"),
    (3, "2344. Minimum Deletions to Make Array Divisible", "Hard"),
    (3, "2521. Distinct Prime Factors of Product of Array", "Hard"),
    (3, "2523. Closest Prime Numbers in Range", "Hard")
]
