sliding_window_problems = [
    (1, "643. Maximum Average Subarray I", "Easy"),
    (1, "1176. Diet Plan Performance", "Easy"),
    (1, "2269. Find the K-Beauty of a Number", "Easy"),
    (2, "3. Longest Substring Without Repeating Characters", "Medium"),
    (2, "209. Minimum Size Subarray Sum", "Medium"),
    (2, "424. Longest Repeating Character Replacement", "Medium"),
    (2, "438. Find All Anagrams in a String", "Medium"),
    (2, "567. Permutation in String", "Medium"),
    (2, "713. Subarray Product Less Than K", "Medium"),
    (2, "904. Fruit Into Baskets", "Medium"),
    (2, "978. Longest Turbulent Subarray", "Medium"),
    (2, "1004. Max Consecutive Ones III", "Medium"),
    (2, "1052. Grumpy Bookstore Owner", "Medium"),
    (2, "1100. Find K-Length Substrings With No Repeated Characters", "Medium"),
    (2, "1151. Minimum Swaps to Group All 1's Together", "Medium"),
    (2, "1208. Get Equal Substrings Within Budget", "Medium"),
    (2, "1248. Count Number of Nice Subarrays", "Medium"),
    (2, "1358. Number of Substrings Containing All Three Characters", "Medium"),
    (2, "1423. Maximum Points You Can Obtain from Cards", "Medium"),
    (2, "1456. Maximum Number of Vowels in a Substring of Given Length", "Medium"),
    (2, "1493. Longest Subarray of 1's After Deleting One Element", "Medium"),
    (2, "1763. Longest Nice Substring", "Medium"),
    (2, "2024. Maximize the Confusion of an Exam", "Medium"),
    (2, "2090. K Radius Subarray Averages", "Medium"),
    (3, "30. Substring with Concatenation of All Words", "Hard"),
    (3, "76. Minimum Window Substring", "Hard"),
    (3, "159. Longest Substring with At Most Two Distinct Characters", "Hard"),
    (3, "239. Sliding Window Maximum", "Hard"),
    (3, "340. Longest Substring with At Most K Distinct Characters", "Hard"),
    (3, "395. Longest Substring with At Least K Repeating Characters", "Hard"),
    (3, "480. Sliding Window Median", "Hard"),
    (3, "632. Smallest Range Covering Elements from K Lists", "Hard"),
    (3, "727. Minimum Window Subsequence", "Hard"),
    (3, "862. Shortest Subarray with Sum at Least K", "Hard"),
    (3, "992. Subarrays with K Different Integers", "Hard"),
    (3, "1040. Moving Stones Until Consecutive II", "Hard"),
    (3, "1234. Replace the Substring for Balanced String", "Hard"),
    (3, "1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit", "Hard"),
    (3, "1498. Number of Subsequences That Satisfy the Given Sum Condition", "Hard"),
    (3, "1610. Maximum Number of Visible Points", "Hard"),
    (3, "1696. Jump Game VI", "Hard")
]
