sliding_window_problems = [
    "3. Longest Substring Without Repeating Characters",
    "30. Substring with Concatenation of All Words",
    "76. Minimum Window Substring",
    "159. Longest Substring with At Most Two Distinct Characters",
    "209. Minimum Size Subarray Sum",
    "239. Sliding Window Maximum",
    "340. Longest Substring with At Most K Distinct Characters",
    "395. Longest Substring with At Least K Repeating Characters",
    "424. Longest Repeating Character Replacement",
    "438. Find All Anagrams in a String",
    "480. Sliding Window Median",
    "567. Permutation in String",
    "632. Smallest Range Covering Elements from K Lists",
    "643. Maximum Average Subarray I",
    "713. Subarray Product Less Than K",
    "727. Minimum Window Subsequence",
    "862. Shortest Subarray with Sum at Least K",
    "904. Fruit Into Baskets",
    "978. Longest Turbulent Subarray",
    "992. Subarrays with K Different Integers",
    "1004. Max Consecutive Ones III",
    "1040. Moving Stones Until Consecutive II",
    "1052. Grumpy Bookstore Owner",
    "1100. Find K-Length Substrings With No Repeated Characters",
    "1151. Minimum Swaps to Group All 1's Together",
    "1176. Diet Plan Performance",
    "1208. Get Equal Substrings Within Budget",
    "1234. Replace the Substring for Balanced String",
    "1248. Count Number of Nice Subarrays",
    "1358. Number of Substrings Containing All Three Characters",
    "1423. Maximum Points You Can Obtain from Cards",
    "1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit",
    "1456. Maximum Number of Vowels in a Substring of Given Length",
    "1493. Longest Subarray of 1's After Deleting One Element",
    "1498. Number of Subsequences That Satisfy the Given Sum Condition",
    "1610. Maximum Number of Visible Points",
    "1696. Jump Game VI",
    "1763. Longest Nice Substring",
    "2024. Maximize the Confusion of an Exam",
    "2090. K Radius Subarray Averages",
    "2269. Find the K-Beauty of a Number"
]
