stack_problems = [
    "20. Valid Parentheses",
    "22. Generate Parentheses",
    "32. Longest Valid Parentheses",
    "42. Trapping Rain Water",
    "71. Simplify Path",
    "84. Largest Rectangle in Histogram",
    "85. Maximal Rectangle",
    "94. Binary Tree Inorder Traversal",
    "103. Binary Tree Zigzag Level Order Traversal",
    "144. Binary Tree Preorder Traversal",
    "145. Binary Tree Postorder Traversal",
    "150. Evaluate Reverse Polish Notation",
    "155. Min Stack",
    "173. Binary Search Tree Iterator",
    "224. Basic Calculator",
    "225. Implement Stack using Queues",
    "227. Basic Calculator II",
    "232. Implement Queue using Stacks",
    "234. Palindrome Linked List",
    "255. Verify Preorder Sequence in Binary Search Tree",
    "316. Remove Duplicate Letters",
    "331. Verify Preorder Serialization of a Binary Tree",
    "341. Flatten Nested List Iterator",
    "385. Mini Parser",
    "394. Decode String",
    "402. Remove K Digits",
    "456. 132 Pattern",
    "496. Next Greater Element I",
    "503. Next Greater Element II",
    "636. Exclusive Time of Functions",
    "682. Baseball Game",
    "735. Asteroid Collision",
    "739. Daily Temperatures",
    "844. Backspace String Compare",
    "856. Score of Parentheses",
    "880. Decoded String at Index",
    "901. Online Stock Span",
    "907. Sum of Subarray Minimums",
    "921. Minimum Add to Make Parentheses Valid",
    "946. Validate Stack Sequences",
    "1019. Next Greater Node In Linked List",
    "1047. Remove All Adjacent Duplicates In String",
    "1209. Remove All Adjacent Duplicates in String II",
    "1249. Minimum Remove to Make Valid Parentheses",
    "1472. Design Browser History",
    "1544. Make The String Great",
    "1673. Find the Most Competitive Subsequence",
    "1762. Buildings With an Ocean View",
    "2390. Removing Stars From a String"
]
