stack_problems = [
    (1, "20. Valid Parentheses", "Easy"),
    (1, "155. Min Stack", "Easy"),
    (1, "225. Implement Stack using Queues", "Easy"),
    (1, "232. Implement Queue using Stacks", "Easy"),
    (1, "496. Next Greater Element I", "Easy"),
    (1, "682. Baseball Game", "Easy"),
    (1, "844. Backspace String Compare", "Easy"),
    (1, "1047. Remove All Adjacent Duplicates In String", "Easy"),
    (1, "1544. Make The String Great", "Easy"),
    (1, "2390. Removing Stars From a String", "Easy"),
    (2, "22. Generate Parentheses", "Medium"),
    (2, "71. Simplify Path", "Medium"),
    (2, "94. Binary Tree Inorder Traversal", "Medium"),
    (2, "103. Binary Tree Zigzag Level Order Traversal", "Medium"),
    (2, "144. Binary Tree Preorder Traversal", "Medium"),
    (2, "145. Binary Tree Postorder Traversal", "Medium"),
    (2, "150. Evaluate Reverse Polish Notation", "Medium"),
    (2, "173. Binary Search Tree Iterator", "Medium"),
    (2, "227. Basic Calculator II", "Medium"),
    (2, "234. Palindrome Linked List", "Medium"),
    (2, "255. Verify Preorder Sequence in Binary Search Tree", "Medium"),
    (2, "316. Remove Duplicate Letters", "Medium"),
    (2, "331. Verify Preorder Serialization of a Binary Tree", "Medium"),
    (2, "341. Flatten Nested List Iterator", "Medium"),
    (2, "394. Decode String", "Medium"),
    (2, "402. Remove K Digits", "Medium"),
    (2, "456. 132 Pattern", "Medium"),
    (2, "503. Next Greater Element II", "Medium"),
    (2, "636. Exclusive Time of Functions", "Medium"),
    (2, "735. Asteroid Collision", "Medium"),
    (2, "739. Daily Temperatures", "Medium"),
    (2, "856. Score of Parentheses", "Medium"),
    (2, "880. Decoded String at Index", "Medium"),
    (2, "901. Online Stock Span", "Medium"),
    (2, "921. Minimum Add to Make Parentheses Valid", "Medium"),
    (2, "946. Validate Stack Sequences", "Medium"),
    (2, "1019. Next Greater Node In Linked List", "Medium"),
    (2, "1209. Remove All Adjacent Duplicates in String II", "Medium"),
    (2, "1249. Minimum Remove to Make Valid Parentheses", "Medium"),
    (2, "1472. Design Browser History", "Medium"),
    (2, "1673. Find the Most Competitive Subsequence", "Medium"),
    (2, "1762. Buildings With an Ocean View", "Medium"),
    (3, "32. Longest Valid Parentheses", "Hard"),
    (3, "42. Trapping Rain Water", "Hard"),
    (3, "84. Largest Rectangle in Histogram", "Hard"),
    (3, "85. Maximal Rectangle", "Hard"),
    (3, "224. Basic Calculator", "Hard"),
    (3, "385. Mini Parser", "Hard"),
    (3, "907. Sum of Subarray Minimums", "Hard")
]
