trees_problems = [
    (1, "94. Binary Tree Inorder Traversal", "Easy"),
    (1, "100. Same Tree", "Easy"),
    (1, "101. Symmetric Tree", "Easy"),
    (1, "104. Maximum Depth of Binary Tree", "Easy"),
    (1, "108. Convert Sorted Array to Binary Search Tree", "Easy"),
    (1, "110. Balanced Binary Tree", "Easy"),
    (1, "111. Minimum Depth of Binary Tree", "Easy"),
    (1, "112. Path Sum", "Easy"),
    (1, "144. Binary Tree Preorder Traversal", "Easy"),
    (1, "145. Binary Tree Postorder Traversal", "Easy"),
    (1, "226. Invert Binary Tree", "Easy"),
    (1, "235. Lowest Common Ancestor of a Binary Search Tree", "Easy"),
    (1, "257. Binary Tree Paths", "Easy"),
    (1, "404. Sum of Left Leaves", "Easy"),
    (1, "501. Find Mode in Binary Search Tree", "Easy"),
    (1, "530. Minimum Absolute Difference in BST", "Easy"),
    (1, "543. Diameter of Binary Tree", "Easy"),
    (1, "572. Subtree of Another Tree", "Easy"),
    (1, "617. Merge Two Binary Trees", "Easy"),
    (1, "637. Average of Levels in Binary Tree", "Easy"),
    (1, "653. Two Sum IV - Input is a BST", "Easy"),
    (1, "700. Search in a Binary Search Tree", "Easy"),
    (1, "783. Minimum Distance Between BST Nodes", "Easy"),
    (1, "872. Leaf-Similar Trees", "Easy"),
    (1, "897. Increasing Order Search Tree", "Easy"),
    (1, "938. Range Sum of BST", "Easy"),
    (1, "965. Univalued Binary Tree", "Easy"),
    (1, "1022. Sum of Root To Leaf Binary Numbers", "Easy"),
    (2, "95. Unique Binary Search Trees II", "Medium"),
    (2, "96. Unique Binary Search Trees", "Medium"),
    (2, "98. Validate Binary Search Tree", "Medium"),
    (2, "102. Binary Tree Level Order Traversal", "Medium"),
    (2, "103. Binary Tree Zigzag Level Order Traversal", "Medium"),
    (2, "105. Construct Binary Tree from Preorder and Inorder Traversal", "Medium"),
    (2, "106. Construct Binary Tree from Inorder and Postorder Traversal", "Medium"),
    (2, "107. Binary Tree Level Order Traversal II", "Medium"),
    (2, "113. Path Sum II", "Medium"),
    (2, "114. Flatten Binary Tree to Linked List", "Medium"),
    (2, "116. Populating Next Right Pointers in Each Node", "Medium"),
    (2, "117. Populating Next Right Pointers in Each Node II", "Medium"),
    (2, "129. Sum Root to Leaf Numbers", "Medium"),
    (2, "199. Binary Tree Right Side View", "Medium"),
    (2, "222. Count Complete Tree Nodes", "Medium"),
    (2, "230. Kth Smallest Element in a BST", "Medium"),
    (2, "236. Lowest Common Ancestor of a Binary Tree", "Medium"),
    (2, "437. Path Sum III", "Medium"),
    (2, "449. Serialize and Deserialize BST", "Medium"),
    (2, "450. Delete Node in a BST", "Medium"),
    (2, "508. Most Frequent Subtree Sum", "Medium"),
    (2, "513. Find Bottom Left Tree Value", "Medium"),
    (2, "515. Find Largest Value in Each Tree Row", "Medium"),
    (2, "538. Convert BST to Greater Tree", "Medium"),
    (2, "623. Add One Row to Tree", "Medium"),
    (2, "652. Find Duplicate Subtrees", "Medium"),
    (2, "654. Maximum Binary Tree", "Medium"),
    (2, "662. Maximum Width of Binary Tree", "Medium"),
    (2, "669. Trim a Binary Search Tree", "Medium"),
    (2, "701. Insert into a Binary Search Tree", "Medium"),
    (2, "814. Binary Tree Pruning", "Medium"),
    (2, "863. All Nodes Distance K in Binary Tree", "Medium"),
    (2, "958. Check Completeness of a Binary Tree", "Medium"),
    (2, "979. Distribute Coins in Binary Tree", "Medium"),
    (2, "998. Maximum Binary Tree II", "Medium"),
    (2, "1008. Construct Binary Search Tree from Preorder Traversal", "Medium"),
    (2, "1026. Maximum Difference Between Node and Ancestor", "Medium"),
    (2, "1038. Binary Search Tree to Greater Sum Tree", "Medium"),
    (2, "1104. Path In Zigzag Labelled Binary Tree", "Medium"),
    (2, "1261. Find Elements in a Contaminated Binary Tree", "Medium"),
    (2, "1302. Deepest Leaves Sum", "Medium"),
    (2, "1305. All Elements in Two Binary Search Trees", "Medium"),
    (2, "1315. Sum of Nodes with Even-Valued Grandparent", "Medium"),
    (2, "1325. Delete Leaves With a Given Value", "Medium"),
    (2, "1339. Maximum Product of Splitted Binary Tree", "Medium"),
    (2, "1367. Linked List in Binary Tree", "Medium"),
    (2, "1448. Count Good Nodes in Binary Tree", "Medium"),
    (2, "1457. Pseudo-Palindromic Paths in a Binary Tree", "Medium"),
    (2, "1609. Even Odd Tree", "Medium"),
    (3, "99. Recover Binary Search Tree", "Hard"),
    (3, "124. Binary Tree Maximum Path Sum", "Hard"),
    (3, "297. Serialize and Deserialize Binary Tree", "Hard"),
    (3, "337. House Robber III", "Hard"),
    (3, "687. Longest Univalue Path", "Hard"),
    (3, "968. Binary Tree Cameras", "Hard"),
    (3, "987. Vertical Order Traversal of a Binary Tree", "Hard"),
    (3, "1080. Insufficient Nodes in Root to Leaf Paths", "Hard"),
    (3, "1110. Delete Nodes And Return Forest", "Hard"),
    (3, "1123. Lowest Common Ancestor of Deepest Leaves", "Hard"),
    (3, "1372. Longest ZigZag Path in a Binary Tree", "Hard"),
    (3, "1373. Maximum Sum BST in Binary Tree", "Hard"),
    (3, "1530. Number of Good Leaf Nodes Pairs", "Hard"),
    (3, "1973. Count Nodes Equal to Sum of Descendants", "Hard")
]
