trie_problems = [
    (1, "14. Longest Common Prefix", "Easy"),
    (1, "720. Longest Word in Dictionary", "Easy"),
    (2, "139. Word Break", "Medium"),
    (2, "208. Implement Trie (Prefix Tree)", "Medium"),
    (2, "211. Design Add and Search Words Data Structure", "Medium"),
    (2, "421. Maximum XOR of Two Numbers in an Array", "Medium"),
    (2, "648. Replace Words", "Medium"),
    (2, "676. Implement Magic Dictionary", "Medium"),
    (2, "677. Map Sum Pairs", "Medium"),
    (2, "820. Short Encoding of Words", "Medium"),
    (2, "1023. Camelcase Matching", "Medium"),
    (2, "1065. Index Pairs of a String", "Medium"),
    (2, "1233. Remove Sub-Folders from the Filesystem", "Medium"),
    (2, "1268. Search Suggestions System", "Medium"),
    (2, "1804. Implement Trie II (Prefix Tree)", "Medium"),
    (2, "2135. Count Words Obtained After Adding a Letter", "Medium"),
    (2, "2707. Extra Characters in a String", "Medium"),
    (3, "140. Word Break II", "Hard"),
    (3, "212. Word Search II", "Hard"),
    (3, "336. Palindrome Pairs", "Hard"),
    (3, "425. Word Squares", "Hard"),
    (3, "472. Concatenated Words", "Hard"),
    (3, "745. Prefix and Suffix Search", "Hard"),
    (3, "1032. Stream of Characters", "Hard"),
    (3, "1707. Maximum XOR With an Element From Array", "Hard"),
    (3, "1938. Maximum Genetic Difference Query", "Hard"),
    (3, "2227. Encrypt and Decrypt Strings", "Hard"),
    (3, "2416. Sum of Prefix Scores of Strings", "Hard")
]
