trie_problems = [
    "14. Longest Common Prefix",
    "139. Word Break",
    "140. Word Break II",
    "208. Implement Trie (Prefix Tree)",
    "211. Design Add and Search Words Data Structure",
    "212. Word Search II",
    "336. Palindrome Pairs",
    "421. Maximum XOR of Two Numbers in an Array",
    "425. Word Squares",
    "472. Concatenated Words",
    "648. Replace Words",
    "676. Implement Magic Dictionary",
    "677. Map Sum Pairs",
    "720. Longest Word in Dictionary",
    "745. Prefix and Suffix Search",
    "820. Short Encoding of Words",
    "1023. Camelcase Matching",
    "1032. Stream of Characters",
    "1065. Index Pairs of a String",
    "1233. Remove Sub-Folders from the Filesystem",
    "1268. Search Suggestions System",
    "1707. Maximum XOR With an Element From Array",
    "1804. Implement Trie II (Prefix Tree)",
    "1938. Maximum Genetic Difference Query",
    "2135. Count Words Obtained After Adding a Letter",
    "2227. Encrypt and Decrypt Strings",
    "2416. Sum of Prefix Scores of Strings",
    "2707. Extra Characters in a String"
]
