two_d_dp_problems = [
    (1, "62. Unique Paths", "Easy"),
    (1, "63. Unique Paths II", "Easy"),
    (1, "64. Minimum Path Sum", "Easy"),
    (1, "118. Pascal's Triangle", "Easy"),
    (1, "119. Pascal's Triangle II", "Easy"),
    (1, "120. Triangle", "Easy"),
    (1, "221. Maximal Square", "Easy"),
    (1, "256. Paint House", "Easy"),
    (1, "276. Paint Fence", "Easy"),
    (1, "303. Range Sum Query - Immutable", "Easy"),
    (1, "338. Counting Bits", "Easy"),
    (1, "392. Is Subsequence", "Easy"),
    (1, "746. Min Cost Climbing Stairs", "Easy"),
    (1, "1025. Divisor Game", "Easy"),
    (1, "1137. N-th Tribonacci Number", "Easy"),
    (2, "10. Regular Expression Matching", "Medium"),
    (2, "44. Wildcard Matching", "Medium"),
    (2, "72. Edit Distance", "Medium"),
    (2, "97. Interleaving String", "Medium"),
    (2, "115. Distinct Subsequences", "Medium"),
    (2, "123. Best Time to Buy and Sell Stock III", "Medium"),
    (2, "188. Best Time to Buy and Sell Stock IV", "Medium"),
    (2, "265. Paint House II", "Medium"),
    (2, "279. Perfect Squares", "Medium"),
    (2, "309. Best Time to Buy and Sell Stock with Cooldown", "Medium"),
    (2, "312. Burst Balloons", "Medium"),
    (2, "322. Coin Change", "Medium"),
    (2, "368. Largest Divisible Subset", "Medium"),
    (2, "375. Guess Number Higher or Lower II", "Medium"),
    (2, "376. Wiggle Subsequence", "Medium"),
    (2, "377. Combination Sum IV", "Medium"),
    (2, "416. Partition Equal Subset Sum", "Medium"),
    (2, "486. Predict the Winner", "Medium"),
    (2, "494. Target Sum", "Medium"),
    (2, "516. Longest Palindromic Subsequence", "Medium"),
    (2, "518. Coin Change 2", "Medium"),
    (2, "576. Out of Boundary Paths", "Medium"),
    (2, "647. Palindromic Substrings", "Medium"),
    (2, "650. 2 Keys Keyboard", "Medium"),
    (2, "651. 4 Keys Keyboard", "Medium"),
    (2, "673. Number of Longest Increasing Subsequence", "Medium"),
    (2, "688. Knight Probability in Chessboard", "Medium"),
    (2, "712. Minimum ASCII Delete Sum for Two Strings", "Medium"),
    (2, "714. Best Time to Buy and Sell Stock with Transaction Fee", "Medium"),
    (2, "718. Maximum Length of Repeated Subarray", "Medium"),
    (2, "740. Delete and Earn", "Medium"),
    (2, "790. Domino and Tromino Tiling", "Medium"),
    (2, "873. Length of Longest Fibonacci Subsequence", "Medium"),
    (2, "877. Stone Game", "Medium"),
    (2, "931. Minimum Falling Path Sum", "Medium"),
    (2, "983. Minimum Cost For Tickets", "Medium"),
    (2, "1027. Longest Arithmetic Subsequence", "Medium"),
    (2, "1043. Partition Array for Maximum Sum", "Medium"),
    (2, "1105. Filling Bookcase Shelves", "Medium"),
    (2, "1143. Longest Common Subsequence", "Medium"),
    (2, "1277. Count Square Submatrices with All Ones", "Medium"),
    (3, "85. Maximal Rectangle", "Hard"),
    (3, "87. Scramble String", "Hard"),
    (3, "174. Dungeon Game", "Hard"),
    (3, "321. Create Maximum Number", "Hard"),
    (3, "329. Longest Increasing Path in a Matrix", "Hard"),
    (3, "354. Russian Doll Envelopes", "Hard"),
    (3, "363. Max Sum of Rectangle No Larger Than K", "Hard"),
    (3, "403. Frog Jump", "Hard"),
    (3, "410. Split Array Largest Sum", "Hard"),
    (3, "446. Arithmetic Slices II - Subsequence", "Hard"),
    (3, "466. Count The Repetitions", "Hard"),
    (3, "471. Encode String with Shortest Length", "Hard"),
    (3, "472. Concatenated Words", "Hard"),
    (3, "514. Freedom Trail", "Hard"),
    (3, "546. Remove Boxes", "Hard"),
    (3, "552. Student Attendance Record II", "Hard"),
    (3, "629. K Inverse Pairs Array", "Hard"),
    (3, "639. Decode Ways II", "Hard"),
    (3, "664. Strange Printer", "Hard"),
    (3, "689. Maximum Sum of 3 Non-Overlapping Subarrays", "Hard"),
    (3, "691. Stickers to Spell Word", "Hard"),
    (3, "727. Minimum Window Subsequence", "Hard"),
    (3, "730. Count Different Palindromic Subsequences", "Hard"),
    (3, "741. Cherry Pickup", "Hard"),
    (3, "787. Cheapest Flights Within K Stops", "Hard"),
    (3, "818. Race Car", "Hard"),
    (3, "847. Shortest Path Visiting All Nodes", "Hard"),
    (3, "879. Profitable Schemes", "Hard"),
    (3, "887. Super Egg Drop", "Hard"),
    (3, "920. Number of Music Playlists", "Hard"),
    (3, "940. Distinct Subsequences II", "Hard"),
    (3, "956. Tallest Billboard", "Hard"),
    (3, "964. Least Operators to Express Number", "Hard"),
    (3, "968. Binary Tree Cameras", "Hard"),
    (3, "1000. Minimum Cost to Merge Stones", "Hard"),
    (3, "1074. Number of Submatrices That Sum to Target", "Hard"),
    (3, "1092. Shortest Common Supersequence", "Hard"),
    (3, "1125. Smallest Sufficient Team", "Hard"),
    (3, "1220. Count Vowels Permutation", "Hard"),
    (3, "1235. Maximum Profit in Job Scheduling", "Hard"),
    (3, "1240. Tiling a Rectangle with the Fewest Squares", "Hard"),
    (3, "1269. Number of Ways to Stay in the Same Place After Some Steps", "Hard"),
    (3, "1289. Minimum Falling Path Sum II", "Hard"),
    (3, "1326. Minimum Number of Taps to Open to Water a Garden", "Hard"),
    (3, "1340. Jump Game V", "Hard"),
    (3, "1411. Number of Ways to Paint N × 3 Grid", "Hard"),
    (3, "1420. Build Array Where You Can Find The Maximum Exactly K Comparisons", "Hard"),
    (3, "1463. Cherry Pickup II", "Hard"),
    (3, "1473. Paint House III", "Hard"),
    (3, "1510. Stone Game IV", "Hard"),
    (3, "1563. Stone Game V", "Hard"),
    (3, "1575. Count All Possible Routes", "Hard"),
    (3, "1639. Number of Ways to Form a Target String Given a Dictionary", "Hard"),
    (3, "1691. Maximum Height by Stacking Cuboids", "Hard"),
    (3, "1770. Maximum Score from Performing Multiplication Operations", "Hard"),
    (3, "1787. Make the XOR of All Segments Equal to Zero", "Hard"),
    (3, "1866. Number of Ways to Rearrange Sticks With K Sticks Visible", "Hard"),
    (3, "1955. Count Number of Special Subsequences", "Hard"),
    (3, "2060. Check if an Original String Exists Given Two Encoded Strings", "Hard"),
    (3, "2147. Number of Ways to Divide a Long Corridor", "Hard"),
    (3, "2172. Maximum AND Sum of Array", "Hard"),
    (3, "2218. Maximum Value of K Coins From Piles", "Hard"),
    (3, "2272. Substring With Largest Variance", "Hard"),
    (3, "2312. Selling Pieces of Wood", "Hard"),
    (3, "2318. Number of Distinct Roll Sequences", "Hard"),
    (3, "2328. Number of Increasing Paths in a Grid", "Hard"),
    (3, "2407. Longest Increasing Subsequence II", "Hard"),
    (3, "2435. Paths in Matrix Whose Sum Is Divisible by K", "Hard"),
    (3, "2478. Number of Beautiful Partitions", "Hard"),
    (3, "2484. Count Palindromic Subsequences", "Hard"),
    (3, "2585. Number of Ways to Earn Points", "Hard")
]
