two_pointer_problems = [
    "3. Longest Substring Without Repeating Characters",
    "11. Container With Most Water",
    "15. 3Sum",
    "16. 3Sum Closest",
    "19. Remove Nth Node From End of List",
    "26. Remove Duplicates from Sorted Array",
    "27. Remove Element",
    "28. Find the Index of the First Occurrence in a String",
    "42. Trapping Rain Water",
    "61. Rotate List",
    "75. Sort Colors",
    "80. Remove Duplicates from Sorted Array II",
    "86. Partition List",
    "88. Merge Sorted Array",
    "125. Valid Palindrome",
    "141. Linked List Cycle",
    "142. Linked List Cycle II",
    "167. Two Sum II - Input Array Is Sorted",
    "209. Minimum Size Subarray Sum",
    "234. Palindrome Linked List",
    "283. Move Zeroes",
    "344. Reverse String",
    "345. Reverse Vowels of a String",
    "392. Is Subsequence",
    "457. Circular Array Loop",
    "524. Longest Word in Dictionary through Deleting",
    "532. K-diff Pairs in an Array",
    "567. Permutation in String",
    "713. Subarray Product Less Than K",
    "763. Partition Labels",
    "826. Most Profit Assigning Work",
    "844. Backspace String Compare",
    "881. Boats to Save People",
    "917. Reverse Only Letters",
    "923. 3Sum With Multiplicity",
    "925. Long Pressed Name",
    "977. Squares of a Sorted Array",
    "986. Interval List Intersections"
]
