two_pointer_problems = [
    (1, "26. Remove Duplicates from Sorted Array", "Easy"),
    (1, "27. Remove Element", "Easy"),
    (1, "88. Merge Sorted Array", "Easy"),
    (1, "125. Valid Palindrome", "Easy"),
    (1, "141. Linked List Cycle", "Easy"),
    (1, "167. Two Sum II - Input Array Is Sorted", "Easy"),
    (1, "234. Palindrome Linked List", "Easy"),
    (1, "283. Move Zeroes", "Easy"),
    (1, "344. Reverse String", "Easy"),
    (1, "345. Reverse Vowels of a String", "Easy"),
    (1, "392. Is Subsequence", "Easy"),
    (1, "844. Backspace String Compare", "Easy"),
    (1, "917. Reverse Only Letters", "Easy"),
    (1, "925. Long Pressed Name", "Easy"),
    (1, "977. Squares of a Sorted Array", "Easy"),
    (2, "3. Longest Substring Without Repeating Characters", "Medium"),
    (2, "11. Container With Most Water", "Medium"),
    (2, "15. 3Sum", "Medium"),
    (2, "16. 3Sum Closest", "Medium"),
    (2, "19. Remove Nth Node From End of List", "Medium"),
    (2, "28. Find the Index of the First Occurrence in a String", "Medium"),
    (2, "61. Rotate List", "Medium"),
    (2, "75. Sort Colors", "Medium"),
    (2, "80. Remove Duplicates from Sorted Array II", "Medium"),
    (2, "86. Partition List", "Medium"),
    (2, "142. Linked List Cycle II", "Medium"),
    (2, "209. Minimum Size Subarray Sum", "Medium"),
    (2, "457. Circular Array Loop", "Medium"),
    (2, "524. Longest Word in Dictionary through Deleting", "Medium"),
    (2, "532. K-diff Pairs in an Array", "Medium"),
    (2, "567. Permutation in String", "Medium"),
    (2, "713. Subarray Product Less Than K", "Medium"),
    (2, "763. Partition Labels", "Medium"),
    (2, "826. Most Profit Assigning Work", "Medium"),
    (2, "881. Boats to Save People", "Medium"),
    (2, "923. 3Sum With Multiplicity", "Medium"),
    (2, "986. Interval List Intersections", "Medium"),
    (3, "42. Trapping Rain Water", "Hard")
]
