two_d_dp_problems = [
    "10. Regular Expression Matching",
    "44. Wildcard Matching",
    "62. Unique Paths",
    "63. Unique Paths II",
    "64. Minimum Path Sum",
    "72. Edit Distance",
    "85. Maximal Rectangle",
    "87. Scramble String",
    "97. Interleaving String",
    "115. Distinct Subsequences",
    "120. Triangle",
    "123. Best Time to Buy and Sell Stock III",
    "174. Dungeon Game",
    "188. Best Time to Buy and Sell Stock IV",
    "221. Maximal Square",
    "256. Paint House",
    "265. Paint House II",
    "276. Paint Fence",
    "279. Perfect Squares",
    "312. Burst Balloons",
    "321. Create Maximum Number",
    "329. Longest Increasing Path in a Matrix",
    "351. Android Unlock Patterns",
    "354. Russian Doll Envelopes",
    "361. Bomb Enemy",
    "363. Max Sum of Rectangle No Larger Than K",
    "375. Guess Number Higher or Lower II",
    "376. Wiggle Subsequence",
    "377. Combination Sum IV",
    "403. Frog Jump",
    "410. Split Array Largest Sum",
    "416. Partition Equal Subset Sum",
    "418. Sentence Screen Fitting",
    "446. Arithmetic Slices II - Subsequence",
    "464. Can I Win",
    "466. Count The Repetitions",
    "467. Unique Substrings in Wraparound String",
    "471. Encode String with Shortest Length",
    "472. Concatenated Words",
    "474. Ones and Zeroes",
    "486. Predict the Winner",
    "494. Target Sum",
    "514. Freedom Trail",
    "516. Longest Palindromic Subsequence",
    "517. Super Washing Machines",
    "523. Continuous Subarray Sum",
    "546. Remove Boxes",
    "552. Student Attendance Record II",
    "562. Longest Line of Consecutive One in Matrix",
    "568. Maximum Vacation Days",
    "576. Out of Boundary Paths",
    "600. Non-negative Integers without Consecutive Ones",
    "629. K Inverse Pairs Array",
    "638. Shopping Offers",
    "639. Decode Ways II",
    "650. 2 Keys Keyboard",
    "651. 4 Keys Keyboard",
    "664. Strange Printer",
    "673. Number of Longest Increasing Subsequence",
    "688. Knight Probability in Chessboard",
    "689. Maximum Sum of 3 Non-Overlapping Subarrays",
    "691. Stickers to Spell Word",
    "698. Partition to K Equal Sum Subsets",
    "712. Minimum ASCII Delete Sum for Two Strings",
    "714. Best Time to Buy and Sell Stock with Transaction Fee",
    "718. Maximum Length of Repeated Subarray",
    "727. Minimum Window Subsequence",
    "730. Count Different Palindromic Subsequences",
    "740. Delete and Earn",
    "741. Cherry Pickup",
    "750. Number Of Corner Rectangles",
    "764. Largest Plus Sign",
    "787. Cheapest Flights Within K Stops",
    "790. Domino and Tromino Tiling",
    "799. Champagne Tower",
    "801. Minimum Swaps To Make Sequences Increasing",
    "805. Split Array With Same Average",
    "808. Soup Servings",
    "813. Largest Sum of Averages",
    "818. Race Car",
    "823. Binary Trees With Factors",
    "837. New 21 Game",
    "838. Push Dominoes",
    "847. Shortest Path Visiting All Nodes",
    "871. Minimum Number of Refueling Stops",
    "873. Length of Longest Fibonacci Subsequence",
    "877. Stone Game",
    "879. Profitable Schemes",
    "887. Super Egg Drop",
    "898. Bitwise ORs of Subarrays",
    "902. Numbers At Most N Given Digit Set",
    "903. Valid Permutations for DI Sequence",
    "920. Number of Music Playlists",
    "931. Minimum Falling Path Sum",
    "935. Knight Dialer",
    "940. Distinct Subsequences II",
    "943. Find the Shortest Superstring",
    "956. Tallest Billboard",
    "960. Delete Columns to Make Sorted III",
    "964. Least Operators to Express Number",
    "968. Binary Tree Cameras",
    "975. Odd Even Jump",
    "978. Longest Turbulent Subarray",
    "982. Triples with Bitwise AND Equal To Zero",
    "983. Minimum Cost For Tickets",
    "1000. Minimum Cost to Merge Stones",
    "1024. Video Stitching",
    "1027. Longest Arithmetic Subsequence",
    "1039. Minimum Score Triangulation of Polygon",
    "1043. Partition Array for Maximum Sum",
    "1055. Shortest Way to Form String",
    "1058. Minimize Rounding Error to Meet Target",
    "1067. Digit Count in Range",
    "1074. Number of Submatrices That Sum to Target",
    "1092. Shortest Common Supersequence",
    "1125. Smallest Sufficient Team",
    "1130. Minimum Cost Tree From Leaf Values",
    "1139. Largest 1-Bordered Square",
    "1140. Stone Game II",
    "1143. Longest Common Subsequence",
    "1147. Longest Chunked Palindrome Decomposition",
    "1155. Number of Dice Rolls With Target Sum",
    "1187. Make Array Strictly Increasing",
    "1191. K-Concatenation Maximum Sum",
    "1216. Valid Palindrome III",
    "1223. Dice Roll Simulation",
    "1230. Toss Strange Coins",
    "1235. Maximum Profit in Job Scheduling",
    "1240. Tiling a Rectangle with the Fewest Squares",
    "1246. Palindrome Removal",
    "1259. Handshakes That Don't Cross",
    "1269. Number of Ways to Stay in the Same Place After Some Steps",
    "1277. Count Square Submatrices with All Ones",
    "1278. Palindrome Partitioning III",
    "1289. Minimum Falling Path Sum II",
    "1292. Maximum Side Length of a Square with Sum Less than or Equal to Threshold",
    "1301. Number of Paths with Max Score",
    "1312. Minimum Insertion Steps to Make a String Palindrome",
    "1320. Minimum Distance to Type a Word Using Two Fingers",
    "1326. Minimum Number of Taps to Open to Water a Garden",
    "1335. Minimum Difficulty of a Job Schedule",
    "1339. Maximum Product of Splitted Binary Tree",
    "1340. Jump Game V",
    "1349. Maximum Students Taking Exam",
    "1359. Count All Valid Pickup and Delivery Options",
    "1363. Largest Multiple of Three",
    "1367. Linked List in Binary Tree",
    "1372. Longest ZigZag Path in a Binary Tree",
    "1373. Maximum Sum BST in Binary Tree",
    "1377. Frog Position After T Seconds",
    "1388. Pizza With 3n Slices",
    "1392. Longest Happy Prefix",
    "1397. Find All Good Strings",
    "1402. Reducing Dishes",
    "1406. Stone Game III",
    "1411. Number of Ways to Paint N × 3 Grid",
    "1416. Restore The Array",
    "1420. Build Array Where You Can Find The Maximum Exactly K Comparisons",
    "1425. Constrained Subsequence Sum",
    "1434. Number of Ways to Wear Different Hats to Each Other",
    "1444. Number of Ways of Cutting a Pizza",
    "1449. Form Largest Integer With Digits That Add up to Target",
    "1458. Max Dot Product of Two Subsequences",
    "1463. Cherry Pickup II",
    "1473. Paint House III",
    "1478. Allocate Mailboxes",
    "1483. Kth Ancestor of a Tree Node",
    "1494. Parallel Courses II",
    "1510. Stone Game IV",
    "1524. Number of Sub-arrays With Odd Sum",
    "1526. Minimum Number of Increments on Subarrays to Form a Target Array",
    "1548. The Most Similar Path in a Graph",
    "1549. The Most Recent Orders for Each Product",
    "1553. Minimum Number of Days to Eat N Oranges",
    "1563. Stone Game V",
    "1569. Number of Ways to Reorder Array to Get Same BST",
    "1575. Count All Possible Routes",
    "1594. Maximum Non Negative Product in a Matrix",
    "1595. Minimum Cost to Connect Two Groups of Points",
    "1626. Best Team With No Conflicts",
    "1639. Number of Ways to Form a Target String Given a Dictionary",
    "1641. Count Sorted Vowel Strings",
    "1643. Kth Smallest Instructions",
    "1653. Minimum Deletions to Make String Balanced",
    "1659. Maximize Grid Happiness",
    "1664. Ways to Make a Fair Array",
    "1671. Minimum Number of Removals to Make Mountain Array",
    "1690. Stone Game VII",
    "1691. Maximum Height by Stacking Cuboids",
    "1692. Count Ways to Distribute Candies",
    "1696. Jump Game VI",
    "1706. Where Will the Ball Fall",
    "1723. Find Minimum Time to Finish All Jobs",
    "1727. Largest Submatrix With Rearrangements",
    "1745. Palindrome Partitioning IV",
    "1746. Maximum Subarray Sum After One Operation",
    "1751. Maximum Number of Events That Can Be Attended II",
    "1770. Maximum Score from Performing Multiplication Operations",
    "1771. Maximize Palindrome Length From Subsequences",
    "1774. Closest Dessert Cost",
    "1787. Make the XOR of All Segments Equal to Zero",
    "1799. Maximize Score After N Operations",
    "1815. Maximum Number of Groups Getting Fresh Donuts",
    "1824. Minimum Sideway Jumps",
    "1829. Maximum XOR for Each Query",
    "1830. Minimum Number of Operations to Make String Sorted",
    "1840. Maximum Building Height",
    "1866. Number of Ways to Rearrange Sticks With K Sticks Visible",
    "1872. Stone Game VIII",
    "1883. Minimum Skips to Arrive at Meeting On Time",
    "1884. Egg Drop With 2 Eggs and N Floors",
    "1889. Minimum Space Wasted From Packaging",
    "1895. Largest Magic Square",
    "1900. The Earliest and Latest Rounds Where Players Compete",
    "1911. Maximum Alternating Subsequence Sum",
    "1931. Painting a Grid With Three Different Colors",
    "1937. Maximum Number of Points with Cost",
    "1944. Number of Visible People in a Queue",
    "1955. Count Number of Special Subsequences",
    "1959. Minimum Total Space Wasted With K Resizing Operations",
    "1960. Maximum Product of the Length of Two Palindromic Substrings",
    "1977. Number of Ways to Separate Numbers",
    "1981. Minimize the Difference Between Target and Chosen Elements",
    "1987. Number of Unique Good Subsequences",
    "1995. Count Special Quadruplets",
    "1997. First Day Where You Have Been in All the Rooms",
    "2002. Maximum Product of the Length of Two Palindromic Subsequences",
    "2008. Maximum Earnings From Taxi",
    "2009. Minimum Number of Operations to Make Array Continuous",
    "2014. Longest Subsequence Repeated k Times",
    "2019. The Score of Students Solving Math Expression",
    "2029. Stone Game IX",
    "2035. Partition Array Into Two Arrays to Minimize Sum Difference",
    "2036. Maximum Alternating Subarray Sum",
    "2054. Two Best Non-Overlapping Events",
    "2060. Check if an Original String Exists Given Two Encoded Strings",
    "2111. Minimum Operations to Make the Array K-Increasing",
    "2140. Solving Questions With Brainpower",
    "2147. Number of Ways to Divide a Long Corridor",
    "2172. Maximum AND Sum of Array",
    "2179. Count Good Triplets in an Array",
    "2188. Minimum Time to Finish the Race",
    "2209. Minimum White Tiles After Covering With Carpets",
    "2218. Maximum Value of K Coins From Piles",
    "2222. Number of Ways to Select Buildings",
    "2240. Number of Ways to Buy Pens and Pencils",
    "2245. Maximum Trailing Zeros in a Cornered Path",
    "2246. Longest Path With Different Adjacent Characters",
    "2266. Count Number of Texts",
    "2267. Check if There Is a Valid Parentheses String Path",
    "2272. Substring With Largest Variance",
    "2291. Maximum Profit From Trading Stocks",
    "2305. Fair Distribution of Cookies",
    "2312. Selling Pieces of Wood",
    "2313. Minimum Flips in Binary Tree to Get Result",
    "2318. Number of Distinct Roll Sequences",
    "2320. Count Number of Ways to Place Houses",
    "2321. Maximum Score Of Spliced Array",
    "2327. Number of People Aware of a Secret",
    "2328. Number of Increasing Paths in a Grid",
    "2370. Longest Ideal Subsequence",
    "2376. Count Special Integers",
    "2400. Number of Ways to Reach a Position After Exactly k Steps",
    "2407. Longest Increasing Subsequence II",
    "2431. Maximize Total Beauty of the Garden",
    "2435. Paths in Matrix Whose Sum Is Divisible by K",
    "2463. Minimum Total Distance Traveled",
    "2466. Count Ways To Build Good Strings",
    "2472. Maximum Number of Non-overlapping Palindrome Substrings",
    "2478. Number of Beautiful Partitions",
    "2484. Count Palindromic Subsequences",
    "2518. Number of Great Partitions",
    "2522. Partition String Into Substrings With Values at Most K",
    "2556. Disconnect Path in a Binary Matrix by at Most One Flip",
    "2572. Count the Number of Square-Free Subsets",
    "2585. Number of Ways to Earn Points"
]

